### ISSUE TITLE
Error when git not installed

### ISSUE THREAD

**Issue by neuralyzer** [ICB-DCM/pyABC#1]
``import pyabc`` fails when git is not installed due to en error in the gitpython package.
Steps to reproduce:
```
import pyabc
```

**Comment by yannikschaelte** [comment]
can something be done about this apart from telling in the documentation that git must be installed?

**Comment by neuralyzer** [comment]
Would probably nice to recommend this. However, git is not essential for pyABC. This is rather an optional feature. pyABC stores the git hash of the current repo if there is one. This should help to make results more reproducible but is not essential in any way. I'd suggest a simple fix which checks for the import error so that git becomes totally optional

**Comment by elbaraim** [comment]
I would suggest to include this somehow in the setup.py, like it is done for, e.g.
extra_requires={"R": ["rpy2"]}

What do you think?

**Comment by neuralyzer** [comment]
I think this is a really good idea. We would also need to document it properly in addition.

**Comment by neuralyzer** [comment]
I think the new git_hash function should do the trick:
https://github.com/ICB-DCM/pyABC/blob/master/pyabc/storage/history.py#L48

**Comment by yannikschaelte** [comment]
yes, seems to work.

**Comment by neuralyzer** [comment]
Closed via commit 22100faf29e6ea909c80925adc45b40f4924fa36
