### ISSUE TITLE
QuantileEpsilon

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#10]
Generalize the MedianEpsilon to allow arbitrary quantiles, with both weighted and non-weighted distances.

**Comment by neuralyzer** [comment]
Very much in favor of this feature!

**Comment by yannikschaelte** [comment]
Remains to check validity (compare with MedianEpsilon!) and eventually reduce code duplicity with MedianEpsilon.
Check weighted_statistics, in particular whether the line median = sp.interp(.5, cs - .5 * weights, points) is correct.
