### ISSUE TITLE
Data plots

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#110]
I think it would be really good to have some data plots of observed vs. simulated summary statistics (or directly model outputs, but these aren't ever stored atm ...). I'm not sure how feasible that is since the data format can be rather arbitrary (dimensions, arrays, dataframes), but maybe one can cover some cases to offer default data plots for easy assessment of how good we are able to fit the data.

**Comment by EmadAlamoudi** [comment]
Is both observed and simulated data usually have the same datatype, or they may have different datatypes?

**Comment by yannikschaelte** [comment]
they should have the exact same form. e.g. numpy arrays, pandas data frames etc.. the keys of the dictionary should in particular be the same.

sometimes it can happen that there are vectors of different length (e.g. when measurements are taken at random time points, or the number of events is not known a-priori), but usually they have the same format.

**Comment by yannikschaelte** [comment]
a first rudimentary data plotting routine is now implemented via #169. more can be added upon a need-basis
