### ISSUE TITLE
Distance updates for AdaptivePNorm take a very long time when the fraction of accepted samples is small.

### ISSUE THREAD

**Issue by Pat-Laub** [ICB-DCM/pyABC#114]
Firstly, thanks very much for creating this great library!

When using AdaptivePNorm with a small `min_acceptance_rate` (< 1e-3), I noticed that sometimes pyABC spent more time running some of the update steps (i.e. some of the unparallelised steps) than it did running the parallel simulation steps. 

In particular, in smc.py at the line 
    `self.distance_function.update(t + 1, sample.all_sum_stats)`
it would spent a long time just evaluating the `sample.all_sum_stats`. This is because it would load all accepted and rejected summary statistics in order to calculate (for example) the sample standard deviations of each summary statistic without bias towards accepted particles.

This procedure is fine, however it seems that calculating the sample standard deviation with **all** of the particles can be a bit of overkill when the number of rejected particles gets into the hundreds of thousands or millions. I made some modification in a fork which allows one to update the distance using a smaller sample of particles than the entire history; I hope this is useful.

**Comment by yannikschaelte** [comment]
Hi, thanks for your message and pull request. We so far never had the problem of overly many samples, but for small simulation times this can apparently happen, as in your case. Thanks for reporting this.

In such a situation, a "representative sample" of accepted and rejected summary statistics should indeed suffice. Thus, your pull request is most welcome and we will definitely include it ASAP.

Maybe we will make minor modifications, like allowing to alter the number of samples taken, basing the default on a multiple of the number of accepted particles, and making the limitation optional. One could also think about not memorizing samples at all as soon as a threshold, say 1000, has been hit, in the first place.

> I noticed that sometimes pyABC spent more time running some of the update steps (i.e. some of the unparallelised steps) than it did running the parallel simulation steps.

When you notice more things of this kind, please let us know. We are aware of some issues with e.g. database access, which we could then address.

**Comment by yannikschaelte** [comment]
closed via #130
