### ISSUE TITLE
Size parameter unused in plot_confidence_intervals

### ISSUE THREAD

**Issue by fbkarsdorp** [ICB-DCM/pyABC#123]
The function `pyabc.visualization.plot_confidence_intervals` defines the parameter `size` to specify the figure size, but the parameter values aren't used to create the figure:

https://github.com/ICB-DCM/pyABC/blob/f23f0ff8d430a8ce0a0c8253b45e19add9121992/pyabc/visualization/confidence.py#L10-L16

https://github.com/ICB-DCM/pyABC/blob/f23f0ff8d430a8ce0a0c8253b45e19add9121992/pyabc/visualization/confidence.py#L48-L49

**Comment by yannikschaelte** [comment]
Thank you very much for your comment! We seem to have forgotten that. It should be in the develop branch already and will hopefully soon be merged!

**Comment by fbkarsdorp** [comment]
Great! Thanks!

**Comment by yannikschaelte** [comment]
Just as an afterthought: We meanwhile replaced "confidence" by "credible" in the kind of function as discussed here, since we are in a Bayesian context. Sorry for that!
