### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by stefanradev93** [ICB-DCM/pyABC#174]
Hi guys,

I just tried to install pyabc from pip and the installation fails with the following error:

Could not find a version that satisfies the requirement pyarrow>=0.14.1 (from pyabc) (from versions: 0.4.1, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0)No matching distribution found for pyarrow>=0.14.1 (from pyabc)

The latest version of pyarrow in PyPi seems to be 0.14.0, whereas your requirements state that I need at least 0.14.1, which is not installable. 

Thanks in advance!

Stefan

**Comment by yannikschaelte** [comment]
Hi Stefan,

what environment / python distribution are you using? pyarrow 0.14.1 has been published on pypi in July, see https://pypi.org/project/pyarrow/#history. Seems it somehow cannot be found.

Yannik

**Comment by yannikschaelte** [comment]
Potentially, it could be that 1) your ``pip`` refers to python2, in that case use explicitly ``pip3``, or 2) your pip is too old to meet certain requirements, in that case try ``pip install -U pip`` and then again install pyarrow/pyabc, see also https://github.com/apache/arrow/issues/1309.

**Comment by stefanradev93** [comment]
Hi Yannik,

thank for your reply!

Unfortunately, updating pip did not solve it. My environment is:

Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32

I could not reproduce the problem on my Linux PC. Strange...

**Comment by yannikschaelte** [comment]
just checked on a windows computer. there indeed 0.14.0 is the latest, 0.14.1 not available. I will look into why the pyarrow guys did that. 

meanwhile, 0.14.0 should defintely work too (it is only necessary when you want to store pandas dataframes as summary statistics. if you use only numpy as data types, then you can even go without). so you could download pyabc from git source and edit the pyarrow requirement in setup.py before installing https://pyabc.readthedocs.io/en/latest/installation.html#git-installation. Or, you could install via ``pip install pyabc --ignore-dependencies``.

**Comment by yannikschaelte** [comment]
Here's their answer: https://issues.apache.org/jira/browse/ARROW-6765?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16942839#comment-16942839

So apparently the Windows build broke, but 0.15.0 should be released soon, for the moment you can proceed as described above. Hope that helps.

**Comment by stefanradev93** [comment]
Okay, that worked for now! Thank you!

**Comment by yannikschaelte** [comment]
Great!
