### ISSUE TITLE
An Error in Web-based Visualizations

### ISSUE THREAD

**Issue by cytwill** [ICB-DCM/pyABC#176]
When open the results from abc-server, it suggests a pandas error: AttributeError: 'DataFrame' object has no attribute 'convert_objects'. It seems that the conver_objects method has been deprecated since version 0.21.0. You may need to fix it in order to make  web-based visualization function normally.

**Comment by yannikschaelte** [comment]
Hi! Yes, it is indeed deprecated since 0.21.0. At the moment (0.23.4) it should still work (only print a warning), but we need to change this soon. Thanks for pointing this out!

Yannik

**Comment by yannikschaelte** [comment]
@cytwill I hope it should work now with pyabc release 0.9.17.
