### ISSUE TITLE
Allow not limiting number of jobs in redis in intial iteration

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#229]
For efficiency reaons, we changed to when wanting say 100 particles, we only simulate 100 times in the first iteration, bc there all are accepted anyway. Now a problem occurs when in particular redis workers fail (maybe also when simulations fail?). This must be handled correctly.

**Comment by yannikschaelte** [comment]
see #67 for reference

**Comment by stephanmg** [comment]
fixed in PR #88
