### ISSUE TITLE
Running Redis in protected-mode

### ISSUE THREAD

**Issue by EmadAlamoudi** [ICB-DCM/pyABC#230]
Currently, the Redis server is running in pyabc using the flag `protected-mode no`. This may lead to security issues since the Redis instances will be exposed from any external networks. However, according to the Redis recommendation, this flag can be used:

>  only if you are sure you want clients from other hosts to connect to Redis even if no authentication is configured, nor a specific set of interfaces are explicitly listed using the "bind" directive

**Comment by EmadAlamoudi** [comment]
@yannikschaelte, now we can use the password flag and should match with the server password in the Redis.conf file to establish the communication. However, when specifying a port, an error will occur. :(

**Comment by yannikschaelte** [comment]
Hm, the code looks fine to me. Does it work when you don't specify a port,i.e. use the default 6379?

**Comment by EmadAlamoudi** [comment]
Yes, when not specifying the port, it seems to work fine.

**Comment by yannikschaelte** [comment]
can you post your full commands here to start the server and the worker, and what you put in the Redis.conf?

**Comment by EmadAlamoudi** [comment]
`redis-server` << here you don't need to use the `protected-mode` flag
`abc-redis-worker --host <ip-address> --password <your_redis_password>`

and in the redis.conf, you need to do the follwing:
1- comment the: `bind 127.0.0.1`
2- Uncomment: 
`masterauth your_redis_password`
`requirepass your_redis_password`
3. Finally restart redis by using: `/etc/init.d/redis-server restart`

**Comment by yannikschaelte** [comment]
when you specify a port, do you specify it both in ``redis-server --port 8888`` and the ``abc-redis-worker --host <HOST> --port 8888 --password <PASSWORD>``?

**Comment by yannikschaelte** [comment]
I just tried it out. I took a redis.conf file from here and edited the ``requirepass`` line. Then I just started the redis-server via ``redis-server /path/to/redis.conf --port 8888`` and then a worker via ``abc-redis-worker --port 8888 --password blub``, and I think it worked.

**Comment by EmadAlamoudi** [comment]
Hmm, I thought that no need to specify the path to the `redis.conf`. this is why it was not working before. It works fine when specifying the path. I tried in localhost and between remote host, both are working

**Comment by yannikschaelte** [comment]
Can you add a subsection "Security" to the docs (redis page) with a manual of how to do that? And then a pull request to develop branch, yes.

**Comment by yannikschaelte** [comment]
fixed in #238
