### ISSUE TITLE
Tighter stopping control

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#235]
Sometimes, there occurs an explosion in the number of samples from one iteration to the next, such that a possible minimum acceptance rate is highly violated. In that case, to not waste computational power it would be of interest to have a tighter control, i.e. to stop the sampling process immediately. This will need to be implemented for each sampler separately (and may not always be possible).

**Comment by JanHasenauer** [comment]
Sounds good. Is it already possible to define an upper number of objective function evaluations?

**Comment by yannikschaelte** [comment]
implicity yes, via the minimum acceptance rate parameter (max_obj_evals = pop_size / min_acc_rate).
but since I heard that questions multiple times lately, we might also directly implement a max_obj_evals, then people don't have to do that calculation 😆

**Comment by yannikschaelte** [comment]
done in #236
