### ISSUE TITLE
Allow setting of prepopulation size independently from first population size

### ISSUE THREAD

**Issue by nbungi** [ICB-DCM/pyABC#251]
At the moment the prepopulation has by default the same size as the first population. If one wants to start with a large population size, using the same size for the prepopulation only costs computational time, where a smaller size may suffice to calculate the initial epsilon.

**Comment by yannikschaelte** [comment]
this would indeed be a reasonable feature. we will look into that. maybe one can combine it with specifying a population size for every time point.

**Comment by yannikschaelte** [comment]
@nbungi are you using a fixed population size, or an adaptive population size?

**Comment by nbungi** [comment]
In the beginning I used the ConstantPopulationSize.
At the moment I use the adaptive population size because I think it makes sense to change the population size with time. However, I use a rather small number of  start_nr_particles, such that the prepopulation does not take such much time.

**Comment by yannikschaelte** [comment]
@nbungi would [this](https://github.com/ICB-DCM/pyABC/pull/278/files) solution work for you?

**Comment by nbungi** [comment]
Yes, this is exactly what I was looking for! Thank you for the implementation of nr_calibration_particles
