### ISSUE TITLE
Pass password to RedisEvalParallelSampler

### ISSUE THREAD

**Issue by nbungi** [ICB-DCM/pyABC#255]
I want to use a protected redis-server for the pyabc-pipeline. For this the password for the redis-server has to be passed to the sampler in the python-script. 
I am guessing here, specifically to the RedisEvalParallelSampler(https://github.com/ICB-DCM/pyABC/blob/master/pyabc/sampler/redis_eps/sampler.py)

**Comment by yannikschaelte** [comment]
true, of course. thanks for pointing out!

**Comment by EmadAlamoudi** [comment]
Yes, that makes sense. Thanks @nbungi.

**Comment by yannikschaelte** [comment]
fixed in #256
