### ISSUE TITLE
keep getting the sample particles when sampling from the parameter prior

### ISSUE THREAD

**Issue by HuairenZhang** [ICB-DCM/pyABC#266]
When I used pyABC and sampled particles in a uniform (or normal) distribution space of the parameters, the same particle kept being selected in one generation. This bug still came out regardless single core or multiple cores being used. When single core was used, the same particle was selected immediately. When multiple cores was used, different particles was selected for each core at start, and then it was the same particle kept being selected. I am not sure if the bug comes from the random number generator?
(The system I am using is Ubuntu 18.04)

**Comment by yannikschaelte** [comment]
@HuairenZhang Do you mean there is just one particle that is accepted e.g. 100 times?

For clarification:
* Could you give a minimum code example where the problem you describe occurs?
* Which version of pyABC are use using?
* Do you manually initialize any random number generators?

pyABC itself does not set any random number generator, so when repeating the same analysis, the samples should be different.

**Comment by yannikschaelte** [comment]
Any news on this? I unfortunately cannot reproduce the error.

**Comment by yannikschaelte** [comment]
closed due to inactivity. if problem persists, please reopen!
