### ISSUE TITLE
Allow for initial weights in AdaptiveAggregatedDistance

### ISSUE THREAD

**Issue by nbungi** [ICB-DCM/pyABC#277]
Use case is, if one has a reasonable set of first weights but would want to have them changed adaptively over the following populations. 
Initializing with weights will also skip the prepopulation.

**Comment by yannikschaelte** [comment]
@nbungi would #279 seem reasonable?

**Comment by nbungi** [comment]
Yes, it is! Thank you @yannikschaelte for doing this so quickly!
