### ISSUE TITLE
errors with model selection

### ISSUE THREAD

**Issue by HuairenZhang** [ICB-DCM/pyABC#283]
I was trying to do model selection with pyABC. Following the example given, an error comes out after finishing the calibration sample.

Traceback (most recent call last):
  File "ModelSelection.py", line 310, in <module>
    h = abc.run(minimum_epsilon=0.1, max_nr_populations=5)
  File "/home/linus/.local/lib/python3.6/site-packages/pyabc/smc.py", line 917, in run
    t+1, sample, population, acceptance_rate)
  File "/home/linus/.local/lib/python3.6/site-packages/pyabc/smc.py", line 962, in _prepare_next_iteration
    self._fit_transitions(t)
  File "/home/linus/.local/lib/python3.6/site-packages/pyabc/smc.py", line 1059, in _fit_transitions
    self.transitions[m].fit(particles, w)
IndexError: list index out of range

Please help. Thank you

**Comment by yannikschaelte** [comment]
Hi @HuairenZhang Thanks for pointing that out, that looks indeed like a bug. Can you in addition tell the version of pyABC you use (``python -c 'import pyabc; print(pyabc.__version__)'``)? Did you install from pip or from a github branch?

**Comment by HuairenZhang** [comment]
Hi, we used pip install and it is pyabc-0.9.26

**Comment by HuairenZhang** [comment]
I am sorry that the same error comes out when pyabc-0.10.0 is installed

INFO:Sampler:Parallelizing the sampling on 20 cores.
INFO:History:Start <ABCSMC(id=1, start_time=2020-03-10 15:43:20.840881, end_time=None)>
INFO:ABC:Calibration sample before t=0.
INFO:Epsilon:initial epsilon is 0.18331546980058114
INFO:ABC:t: 0, eps: 0.18331546980058114.
INFO:ABC:Acceptance rate: 100 / 191 = 5.2356e-01, ESS=1.0000e+02.
Traceback (most recent call last):
  File "ModelSelection_test.py", line 329, in <module>
    h = abc.run(minimum_epsilon=0.1, max_nr_populations=1)
  File "/home/linus/.local/lib/python3.6/site-packages/pyabc/smc.py", line 917, in run
    t+1, sample, population, acceptance_rate)
  File "/home/linus/.local/lib/python3.6/site-packages/pyabc/smc.py", line 962, in _prepare_next_iteration
    self._fit_transitions(t)
  File "/home/linus/.local/lib/python3.6/site-packages/pyabc/smc.py", line 1060, in _fit_transitions
    self.transitions[m].fit(particles, w)
IndexError: list index out of range
[1]+  Exit 1

**Comment by yannikschaelte** [comment]
Hi @HuairenZhang , sorry for the delay. I cannot reproduce the error when I run the quickstart example https://pyabc.readthedocs.io/en/latest/examples/quickstart.html, which also does model selection. Which example do you refer to? Can you maybe append the full script you use?

**Comment by HuairenZhang** [comment]
Hi,
Please check the attached file. Both two models work fine with the parameter inference, but for model selection, the error comes out. Do you think this might be due to the different numbers of parameters in the two models?

[ModelSelection_error_to_fix.py.zip](https://github.com/ICB-DCM/pyABC/files/4318585/ModelSelection_error_to_fix.py.zip)

**Comment by HuairenZhang** [comment]
Hi,
Please check the attached file. Both two models work fine with the parameter inference, but for model selection, the error comes out. Do you think this might be due to the different numbers of parameters in the two models?

[error_to_fix.zip](https://github.com/ICB-DCM/pyABC/files/4318611/error_to_fix.zip)

**Comment by yannikschaelte** [comment]
Hi, the problem is that you need to speciffy a transition for each model, so pass ``transitions = [transition.LocalTransition(k_fraction=0.3), transition.LocalTransition(k_fraction=0.3)]``.
Does that resolve the error?

**Comment by HuairenZhang** [comment]
Thank you. The problem is solved. No more error message.

**Comment by yannikschaelte** [comment]
Great!
