### ISSUE TITLE
Issues when creating the ABC_SMC Table 

### ISSUE THREAD

**Issue by cytwill** [ICB-DCM/pyABC#292]
To whom it may concern,

I encountered an operational error when creating new tables:
`OperationalError: (sqlite3.OperationalError) disk I/O error
[SQL: 
CREATE TABLE abc_smc (
	id INTEGER NOT NULL, 
	start_time DATETIME, 
	end_time DATETIME, 
	json_parameters VARCHAR(5000), 
	distance_function VARCHAR(5000), 
	epsilon_function VARCHAR(5000), 
	population_strategy VARCHAR(5000), 
	git_hash VARCHAR(120), 
	PRIMARY KEY (id)
)

]`

Previously, I used the path "sqlite:///estimation.db" to store the data, and it works well. I do not know why this issue happens, could anyone help? thanks very much~

**Comment by yannikschaelte** [comment]
Hi! What exactly did you do? Did you call sql directly, or was this an error when executing the pyabc pipeline in python?

**Comment by cytwill** [comment]
I do not call sqlite directly, I follow the example of parameter inference in pyabc documentation, and just modified the path to be my own path. I am wondering if this could be a conflict between packages?

**Comment by yannikschaelte** [comment]
Hi. Then that's a strange error indeed. "sqlite:///estimation.db" (with 3 ///) would refer to a file "estimation.db" in your current folder. Is that file somehow corrupted? Does the error persist if you choose a different file name? It could also be a conflict between packages, in that case try updating them, in particular sqlalchemy>=1.3.0.

**Comment by cytwill** [comment]
@yannikschaelte, The database can be built, but can not be written into.  And I tested other name, the issue still exists. It suggests that the error occurs when:
'self.abc.new(path,self.realdata)'
 the path is the location to the sqlite db, realdata are the observation statistics.
Plus, I am running it on a remote server.

**Comment by yannikschaelte** [comment]
can you try running it locally / on a different system?

**Comment by cytwill** [comment]
@yannikschaelte, I am trying it on another machine. I checked the error from the console of the previously failed platform and found such descriptions:

`[IPKernelApp] ERROR | Failed to open SQLite history /mnt/ide0/home/cytwill/.ipython/profile_default/history.sqlite (disk I/O error).
`
Do you have any idea how to fix this issue? It seems relevant to the history file.

**Comment by yannikschaelte** [comment]
do you use an ipython (jupyter) environment? this error seems to indicate something went wrong when creating or reading from some sqlite database file. https://stackoverflow.com/questions/21352285/ipython-operationalerror-disk-i-o-error

How I would proceed: Continue trying on the other machine, and when it works check what is different on the remote machine. So far, we never had problems with the sql database, so I actually think it might be some outdated packages you have on that remote system, or maybe some missing permissions to folders? Or maybe the folder containing the database is not mapped on the system where the abc.new() is called?

**Comment by cytwill** [comment]
Hi, @yannikschaelte  I changed the name of the database, and it started to work somehow, though I remembered I have tried this method before...... I am wondering if it is more stable to use a console to run pyabc instead of ipython?  Also, does pyabc support MPI?

**Comment by yannikschaelte** [comment]
Hi, great to hear. If it works now with a different name, it might be that that old name was registered somewhere wrongly. I hope it will work now reliably. ipython sometimes has a few problems of its own, in particular when using multithreading, so if you use that, better use the console. Of course, directly using the console at least deletes that layer of uncertainty anyway. We have frequently used ipython though, without problems.
pyABC does not support MPI (yet, planned for the future at some point). Currently, the most convenient and best tested distribution engine is the redis sampler https://pyabc.readthedocs.io/en/latest/sampler.html#how-to-set-up-a-redis-based-distributed-cluster.

**Comment by cytwill** [comment]
Ok, thank you so much for the help.

**Comment by yannikschaelte** [comment]
Sure! Let us know when you encounter further problems.
