### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#293]
During sampling, it would be nice to have a status bar showing what percentage of the population size has been sampled already. E.g.
```
Sampling [======                          ] 40%
```
similar to how pymc3 does it.

**Comment by yannikschaelte** [comment]
would need to be implemented per sampler, e.g. like here https://stackoverflow.com/questions/3002085/python-to-print-out-status-bar-and-percentage

**Comment by sisyga** [comment]
Just a hint, you could have a look at the tqdm package:
https://pypi.org/project/tqdm/
I successfully used this in multiprocessing applications.

**Comment by yannikschaelte** [comment]
@sisyga thanks for the suggestion! We also use this one in other tools already.

**Comment by yannikschaelte** [comment]
done in #332
