### ISSUE TITLE
Rarely used feature of more than one simulation per proposal parameter yields errors

### ISSUE THREAD

**Issue by neuralyzer** [ICB-DCM/pyABC#3]
At least the Epsilon adaptations do not work correctly setting more than one simulation per proposed parameter. This feature is rarely used and not currently tested. So probably not a major issue and rarely done by users but we should still fix that of course.

**Comment by yannikschaelte** [comment]
Can you specify the situation in which the problem occurred? Was an error thrown or did you get a wrong epsilon estimate?

**Comment by yannikschaelte** [comment]
so the reasoning would be that  the weights of the **particles** for each model sums to 1? might be a good solution, alternatively one might also want to abstract from the fact that one particle has several distances/summary_statistics, i.e. put all values in one list. 
but certainly works for the moment.
