### ISSUE TITLE
Multi-core sampling does not work on OSX/Linux

### ISSUE THREAD

**Issue by vedantchandra** [ICB-DCM/pyABC#305]
Hello,

I've been having this problem for several months now on OSX, as well as on a Linux server. When trying to run any pyabc sampling with the MultiCore parallel sampler, I invariably get an error ``Process Error: At least one worker is dead``. 

This happens even if I remove all other factors by running a very simple sampling problem - it seems to be an issue with the MultiCore sampler itself, or something wrong on my end that interferes with the sampler. For reference, I'm using a Macbook Pro laptop running OSX Catalina. 

I'd appreciate any help with this! Thank you.

**Comment by yannikschaelte** [comment]
Hi @vedantchandra , does the error occur on both operating systems?

**Comment by yannikschaelte** [comment]
Ah, just re-read . Ok, seems to occur on both. That is of course quite unfortunate, since it prevents you from using parallelization here. Can you provide a minimal example code which produces the error on your system?

**Comment by vedantchandra** [comment]
@yannikschaelte Indeed it's quite strange. I wrote the following MWE:

```
import pyabc
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 1, 100)
y = 3 * x + 2

observed = dict(data = y)

def linear(x, c1, c2):
    return c1 * x + c2

def sim(params):
    return dict(data = linear(x, params['c1'], params['c2']))

def distance(obs, sim):
    return np.mean(np.sqrt((obs['data'] - sim['data'])**2))

priors = pyabc.Distribution(c1 = pyabc.RV("uniform", -10, 20),
                            c2 = pyabc.RV("uniform", -10, 20))

abc = pyabc.ABCSMC(sim, priors,\
                           distance, sampler = pyabc.sampler.MulticoreParticleParallelSampler(n_procs = 2),\
                           population_size = 100, \
                           eps = pyabc.epsilon.QuantileEpsilon(alpha = 0.5))

db = ("sqlite:///test.db")
abc.new(db, observed)

history = abc.run(min_acceptance_rate = 0.01, max_nr_populations = 25)

pyabc.visualization.plot_kde_matrix_highlevel(history);
```

My machine has 4 cores. In my main science use-case, using MultiCore normally causes the 'worker is dead' error every time. With this example, it actually run with `n_procs = 2` for one successful run. However, every subsequent run crashed my kernel with no error or explanation. 

I ran these tests in Jupyter Notebook, but in my main use-case I've tried this in native Python code as well to no avail. I also repeatedly get a `INFO:numexpr.utils:NumExpr defaulting to 8 threads` warning.

I appreciate your help with this!

**Comment by yannikschaelte** [comment]
Hi,

> My machine has 4 cores. In my main science use-case, using MultiCore normally causes the 'worker is dead' error every time. With this example, it actually run with `n_procs = 2` for one successful run. However, every subsequent run crashed my kernel with no error or explanation.

I ran your code 6 times on a 4-core machine with 16GB RAM, unfortunately I could not reproduce your error :/ It could either be that processes are shut down due to a system overload (RAM / too many processes), or due to old libraries. A few things I would try out:
* Employ the below OMP_NUM_THREADS fix.
* Monitor CPU / RAM usage
* Update your python environment via `pip install --upgrade --upgrade-strategy eager pyabc`

Further, we usually use not the MulticoreParticleParallelSampler, but the MulticoreEvalParallelSampler, which may do a few more evaluations but overall reduces the runtime by using all available cores better (dynamic scheduling). Thus the latter may be better maintained and more efficient time-wise, but both should be fine.

> I ran these tests in Jupyter Notebook, but in my main use-case I've tried this in native Python code as well to no avail. 

Jupyter sometimes has a few problems with multiprocessing, however only if e.g. the model is swigged from C++. So running natively in python is safer, but we also frequently use jupyter, without any problems.

> I also repeatedly get a `INFO:numexpr.utils:NumExpr defaulting to 8 threads` warning.

This warning has been recently introduced in the numexpr library, which is used by numpy trying to parallelize whenever a slightly more complex algebraic computation is performed. We will fix this in pyABC soon, however you can already now fix it by adding

```python
import os
os.environ['OMP_NUM_THREADS'] = '1'
```
at the top of your script.

Let us know if anything helps!

**Comment by vedantchandra** [comment]
@yannikschaelte thank you for the detailed advice. I followed all your steps, unfortunately now running the above test code yields this error after the sampling is completed, and then python3 crashes and needs to be reopened:

```python
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "pyarrow/types.pxi", line 2638, in pyarrow.lib._unregister_py_extension_types
SystemError: Bad call flags in _PyMethodDef_RawFastCallDict. METH_OLDARGS is no longer supported!
Segmentation fault: 11
```
Testing on my main use-case, it now samples for two iterations before again crashing due to the 'one worker is dead' error. I looked at the traceback and the exact error causing this crash is:

```python
Empty                                     Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/pyabc/sampler/multicorebase.py in get_if_worker_healthy(workers, queue)
    try:
        item = queue.get(True, 5)
        return item

~/opt/anaconda3/lib/python3.7/multiprocessing/queues.py in get(self, block, timeout)
if not self._poll(timeout):
    raise Empty
elif not self._poll():
```

For context, my simulator function is relatively inexpensive and it returns a numpy array around 2x10,000. The distance is computed using this array. Running on the SingleCore sampler it has no problems. Do these error messages lend any insight into what the problem might be? 

Thank you!

**Comment by yannikschaelte** [comment]
Hi, sorry to hear that python3 crashes now. This sounds like this recent (at least macOS) bug, maybe have a look there https://issues.apache.org/jira/browse/ARROW-8684?src=confmacro. If it persists, I can only recommend to set up a clean python installation, e.g. via anaconda venv, where you can control all dependencies.

Does your model with 2x10,000 roughly equivalent the above one with 10,000 steps in x? That number is rather large, so I would definitely make sure the distance is computed efficiently (if it is like above using numpy calls, everything's fine). The larger array size should however not explain why things crash (unless you do indeed observe memory or CPU issues).
Can you try out the `MulticoreEvalParallelSampler` instead? If it also shows the error, one could also think about other parallelization, in particular using Redis or Dask. This would depend on your underlying system then.

**Comment by vedantchandra** [comment]
@yannikschaelte Thank you for the advice, I will try again on a fresh Python install. Since the crash is happening in the multiprocessing module (which I've been having trouble with on my machine anyway), I don't think this is a pyABC issue. Thanks again for all the help!

**Comment by yannikschaelte** [comment]
I would not rule out the possibility that something is wrong with the sampler. Hopefully you can fix it. If you have further questions, happy to discuss.
