### ISSUE TITLE
Stochastic acceptance with custom distance function

### ISSUE THREAD

**Issue by vedantchandra** [ICB-DCM/pyABC#311]
Dear pyABC team,

I am currently using pyABC for a project that uses a custom distance function between N-dimensional simulated points and observed points. I am interested in using the stochastic acceptor under the assumption of model error, however it seems to require using the stochastic kernel distance between summary statistics. Is there a way to implement the stochastic acceptor using my own distance function? Could I somehow reconcile my distance function with the stochastic kernel distance? I do not have any summary statistics, rather I use a distance between the observed and simulated data itself. 

Thank you!

**Comment by yannikschaelte** [comment]
Hi @vedantchandra ,

I assume you have found the [notebook](https://pyabc.readthedocs.io/en/latest/examples/noise.html) on the basic idea of the stochastic acceptance. [Here](https://www.biorxiv.org/content/10.1101/2020.01.30.927004v1) is also an article with background details.

Regarding your questions:
* There is the [SimpleFunctionKernel](https://github.com/ICB-DCM/pyABC/blob/master/pyabc/distance/kernel.py#L78) which can easily wrap around your distance function. You just have to make sure the returned values are on the correct `ret_scale` such that they can be interpreted as coming from a (log-)probability distribution.
* Whether you do or do not have summary statistics does not matter. If you don't define any, pyABC implicitly uses an identity map, i.e. the summary statistics are the model output.

I hope this helps!

**Comment by vedantchandra** [comment]
@yannikschaelte Thank you for the details. Do you know of any other examples that use this acceptor? 

Essentially my function to compute distances is non-trivial and cannot be modified. So I have an immutable mapping between simulated and observed data points and a float distance value. I’m curious if you have any ideas about how to convert this distance into a probability measure that’s suitable for the kernel. Or is there another way to do it?

**Comment by yannikschaelte** [comment]
In general, the idea behind "exact inference with measurement noise" is that one does not require a distance function at all if one has a meaningful noise kernel/distribution that operates directly on the summary statistics. Therefore, the first question would be whether you can circumvent your distance function all together by using an appropriate noise model, e.g. normal noise. This is because in classical statistics, the concept of "distance function" does not really exist nor make sense -- it is only used in ABC to "mock" a missing likelihood function.

This being said, certain distance functions can be interpreted as coming from a probability distribution. E.g., if you have an l2 distance, this corresponds to a log-normal noise probability. An l1 distance corresponds to Laplace noise instead. See also the Supplementary Information to the above paper. So, depending on your exact distance function it may already be possible to interpret it as some log-noise probability. In that case, you can directly use it wrapped inside the `SimpleFunctionKernel` together with the `StochasticAcceptor`, without further ado.

**Comment by vedantchandra** [comment]
Understood! I can now imagine ways to get rid of my distance function. Thank you for your detailed insights, I can close this issue for now.

**Comment by vedantchandra** [comment]
@yannikschaelte I wonder if you have some intuition about the following phenomenon; if whilst using the stochastic acceptor (with the independent normal kernel), the acceptance ratios become very low as T -> 0, is it possible that the error has been underestimated? My simulator uses a black-box error function, so my methodology right now has been to simulate N noisy Monte Carlo samples from the simulator, compute summary statistics, and use the dispersion (standard deviation) of each simulated summary statistic across the MC samples to define the independent normal distance kernel. Is there perhaps a better methodology for situations like this?

As always, I appreciate your help!

**Comment by yannikschaelte** [comment]
Hi @vedantchandra,

> if whilst using the stochastic acceptor (with the independent normal kernel), the acceptance ratios become very low as T -> 0, is it possible that the error has been underestimated?

 when using the stochastic acceptor (together with `eps=Temperature()`), the epsilon value should actually approach 1 in the limit, not 0 as in standard ABC. Does that happen differently for you? If your noise model uses the correct variances, it should be impossible to underestimate the error. The acceptance rates will however decrease definitely over time. If that's a serious problem, one can try to set the desired acceptance rate used in the [`AcceptanceRateScheme`](https://pyabc.readthedocs.io/en/latest/api_epsilon.html#pyabc.epsilon.AcceptanceRateScheme) in the `Temperature` higher.

For complicated models it may be that the theoretical acceptance rate possible that can be achieved is just too low. In that case, one can try changing the `Acceptor.pdf_norm_method` as done [here](https://github.com/yannikschaelte/Study-ABC-Noise/blob/master/study_abc_noise/application_ode2/boehm.py#L77). This function will accept more simulations, at the cost that the sampling weights are more diverse. The constant "20" in l.91 may need to be changed, this depends a bit on the model. Sorry, this part has not yet made it into pyABC, but should still be usable.

> My simulator uses a black-box error function, so my methodology right now has been to simulate N noisy Monte Carlo samples from the simulator, compute summary statistics, and use the dispersion (standard deviation) of each simulated summary statistic across the MC samples to define the independent normal distance kernel. Is there perhaps a better methodology for situations like this?

So you draw those N samples from the simulator for parameters sampled from the prior?

**Comment by vedantchandra** [comment]
@yannikschaelte 

1) Interesting. Yes, the epsilon converges to zero, but the last step has an extremely low acceptance rate (around 1 in 100,000). 

2) I'll take a look at that notebook. This isn't too much of a problem for me, I was just curious if it was possible to extract more effective samples with the same computation time. 

3) No, I draw N samples for some initial guess of parameters. My reasoning is that this should somewhat estimate the internal variance of the summary statistics. I don't expect the behaviour of the variances to change too much when the parameters change.

**Comment by yannikschaelte** [comment]
@vedantchandra please find here https://pyabc.readthedocs.io/en/develop/examples/noise.html now also an example of estimating noise parameters on-the-fly.
