### ISSUE TITLE
Error in openFeather(path) : Invalid: Not a feather file

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#315]
When exporting the database to feather format, e.g. via
```sh
$ abc-export --db test.db --out test.feather --format feather --generation all
```
and importing in R via
```R
> library('feather')
> data = read_feather('/tmp/test.feather')
```
we get
```
Error in openFeather(path) : Invalid: Not a feather file
```
this happens only for some versions, e.g. pyabc 0.10.3, pandas 1.0.4, R 3.6.3.

**Comment by yannikschaelte** [comment]
This error can be reproduced quite simply:
```python
import pandas as pd
df = pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]})
df.to_feather('out.f')
```
same error

**Comment by yannikschaelte** [comment]
See also https://github.com/pandas-dev/pandas/issues/34670

**Comment by yannikschaelte** [comment]
Closing here as this is not a problem of pyabc. One should use the latest arrow packages (or feather, at some point) on python and R side, see the above link.

**Comment by nbungi** [comment]
Here is a work-around, as I encounter this issue even though I am using the latest arrow(2.0.0)/feather(0.3.5) packages in R.
Using pyarrow(2.0.0) one can read and rewrite the feather file in "version 1", which is then readable in R.
`import pyarrow.feather as feather
feather_db = feather.read_feather('my_db.feather')
feather.write_feather(feather_db, 'my_db_v1.feather', version=1)`

**Comment by chunjie-sam-liu** [comment]
Thanks to @nbungi, I find this link https://arrow.apache.org/docs/python/feather.html.
> Writing Version 1 (V1) Files
>For compatibility with libraries without support for Version 2 files, you can write the version 1 format by passing version=1 to write_feather. We intend to maintain read support for V1 for the foreseeable future.

**Comment by JohannesWiesner** [comment]
For me, when using `version=1` and I try to load the `.feather` file in R-Studio, RStudio crashes.

**Comment by yannikschaelte** [comment]
The feather format appears to be somewhat cumbersome, with different tools implementing/supporting different versions etc.. Not sure what lead to this error, but just to recapitulate a few options:
* As pointed out above by @nbungi , you can convert to version 1 post-hoc. Alternatively, you can also programmatically extract the database in https://github.com/ICB-DCM/pyABC/blob/main/pyabc/storage/export.py#L83 (this is the function called by `abc-export`) and then apply `pandas.to_feather(filename, version=1)`.
* When importing in R, at least either `feather::read_feather` or `arrow::read_feather` can be used, with the latter in particular for version 1 exports.
