### ISSUE TITLE
Numpy storage correct?

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#32]
In storing and loading dataframes and numpy arrays, there are some build-around functions. I in particular wonder what the line https://github.com/ICB-DCM/pyABC/blob/master/pyabc/storage/numpy_bytes_storage.py#L50 is supposed to do? And could it fail in the special case of size-1 numpy arrays?

**Comment by neuralyzer** [comment]
Very interesting question, indeed. I would also guess that this was about size 1 arrays. You could try to remove the lime tentatively and run the test suite. I'd hope that some test should fail then. If this is not the case, you can try to write a test that makes this function without the line file, then reinsert it and check that it works. The corresponding tests (treating the special cases) seem to be these: https://github.com/ICB-DCM/pyABC/blob/master/test/test_bytesstorage.py

**Comment by yannikschaelte** [comment]
update: yes, the ``type_(...) == ...`` was about 1-dim arrays. These are afterwards converted (hopefully back) to scalar values. In #83, I had to add a test for ``arr.size == 1`` to avoid some future warnings, but the code should be fine as it is.
(On deletion of this part, e.g. string values would remain a numpy array of type string, so that the bytesstorage test of equality of before and after fails).
