### ISSUE TITLE
Question - ideas for constraining parameters to given sum?

### ISSUE THREAD

**Issue by LiBuchauer** [ICB-DCM/pyABC#322]
Hi pyABC team,

just a question this time: I am trying to estimate a composition with pyABC, i.e. I which to constrain my parameters such that they sum to 1. I did not have a clever idea yet on how to accomplish it - I tried assigning a very high distance value to parameter sets which do not comply, but it is not ideal as such sets are still drawn frequently and are thus part of the result. (To specify, I currently draw 5 parameters from uniform distributions between 0 and 1, but would ideally only draw such sets which sum to 1, or be allowed to renormalise them so that they do).

I am looking for a way to either constrain parameters already when defining them or alternatively a way to discard such sets if they are drawn.

Would much appreciate your input, let me know if it is not clear.

Best wishes

Lisa

**Comment by LiBuchauer** [comment]
Actually that question isn't entirely cooked. But if you have any input on how to constrain parameter values in general (e.g. parameter1 <= parameter2) that would be great. I know other MCMC packages allow to define such priors, can it be done in pyABC?

**Comment by yannikschaelte** [comment]
Hi @LiBuchauer ,

in general, if you want to enforce an equality constraint \sum_i^n\theta_i = 1, it may make sense to reduce the dimension by \theta_n = 1 - \sum_i^{n-1}\theta_i. If you have additional constraints, this will of course not sufice.

In pyABC, you can define arbitrary parameter constraints via priors. While the showcases only cover independent priors (`pyrior = Distribution(p0=RV("uniform", a, b-a, p1=...)`, general priors can be defined by deriving directly from the `RV` or `Distribution` classes. https://github.com/ICB-DCM/pyABC/blob/master/pyabc/random_variables.py#L328 In particular, inequality constraints as you defined above should be easy to implement this way. You will just need to overwrite the rvs() and pdf() functions.

Hope this helps!

Yannik

**Comment by LiBuchauer** [comment]
Hi Yannik,

the \theta_n = 1 - \sum_i^{n-1}\theta_i part is (part of) what I meant with not cooked :-).

Thanks for the pointer, I will try and maybe post an example here if I figure it out.

Lisa

**Comment by JesseGarcia562** [comment]
Hello, 

Did you happen to figure out how to do this? I'm trying to do something similar, but I'm having a tough time trying to figure it out. I'm not sure where to start. Is there an example of how to write a custom prior? 

Jesse

**Comment by LiBuchauer** [comment]
Hi Jesse,

sorry for this disappointing answer, but I didn’t follow through with it at the time :-/

Good luck

Lisa

**Comment by yannikschaelte** [comment]
Hi @JesseGarcia562 , for defining custom priors all you have to do is implement a derived [Distribution](https://github.com/ICB-DCM/pyABC/blob/main/pyabc/random_variables.py#L303), and override at least rvs() and pdf() (can be non-normalized), see also https://github.com/ICB-DCM/pyABC/issues/471. An example does not exist afaik unfortunately.
