### ISSUE TITLE
bokeh and bkcharts in setup.py

### ISSUE THREAD

**Issue by dithwick** [ICB-DCM/pyABC#326]
Hi,

Apologies if this has already been addressed (I couldn't find an issue specifically relating to it).

I'm trying to build pyABC 0.10.x for a user using easybuild (https://easybuild.readthedocs.io/en/latest/) which is the build system we use on our facility. I've been looking through the setup.py to make sure I've got the dependencies correct and I noticed that there is:

"bokeh>=0.13.0" and "bkcharts>=0.2"

However according to

https://stackoverflow.com/questions/46237861/importing-python-bokeh-scatter-plots-not-working-cannot-import-default-palette

bokeh should not be updated beyond 0.12.6 if bkcharts is being used. Is bkcharts still being used in the project or should I be installing against bokeh>=0.13.0 and ignoring the bkcharts requirement?

Thanks for your help!

**Comment by yannikschaelte** [comment]
Hi @dithwick, 

thanks for pointing this out! As far as I can see, bkcharts is indeed no longer used, so it should be fine to drop bkcharts and use the latest bokeh. If you encounter errors, bokeh is currently used for the in-time web server https://pyabc.readthedocs.io/en/latest/web_visualization.html (and only there), let us know if you encounter further errors!

We will adjust the setup.py soon.

**Comment by dithwick** [comment]
Hi @yannikschaelte 

No worries and thanks for letting me know. It wonj't be me using it but at least I know where to come back to if the user has a problem.

Should I close the issue or leave it for you to do once setup.py has been updated?

**Comment by yannikschaelte** [comment]
Thanks! We will close it once it's been adjusted.
