### ISSUE TITLE
pyABC Not installable on python 3.6

### ISSUE THREAD

**Issue by NMRobert** [ICB-DCM/pyABC#342]
Hi,

according to the installation documentation at https://pyabc.readthedocs.io/en/latest/installation.html, pyABC should support python 3.6. However... it is not actually possible to install it, due to the dependancy on `jabbar`.

Running `pip install pyabc` yields the following:

```
ERROR: Could not find a version that satisfies the requirement jabbar>=0.0.7 (from pyabc) (from versions: none)
ERROR: No matching distribution found for jabbar>=0.0.7 (from pyabc)
```

and manually trying to install `jabbar` via ` pip install git+https://github.com/yannikschaelte/jabbar.git` yields the following:
```
Collecting git+https://github.com/yannikschaelte/jabbar.git
  Cloning https://github.com/yannikschaelte/jabbar.git to /tmp/pip-req-build-1524sp0q
  Running command git clone -q https://github.com/yannikschaelte/jabbar.git /tmp/pip-req-build-1524sp0q
ERROR: Package 'jabbar' requires a different Python: 3.6.9 not in '>=3.7'
```

As this is just a progress bar, I don't think it's worth it to make this library mandatory, especially as this makes pyABC uninstallable on google colab! Thank you.

**Comment by yannikschaelte** [comment]
Hi @NMRobert , fully agreed. Fix will be in tomorrow.

**Comment by yannikschaelte** [comment]
The jabbar>=0.0.10 package (on pypi) is now also happy to run under python 3.6. Hope that resolves your problems. pyABC requirements will be updated with next merge.

**Comment by yannikschaelte** [comment]
@EmadAlamoudi this should also resolve your problems.

**Comment by NMRobert** [comment]
@yannikschaelte 

Firstly I would like to thank you for a truly impressively fast response. I can confirm that the change is effective - pyABC now installs without issue on 3.6.9, and I can confirm that the quickstart tutorial executes correctly in its entirety.
