### ISSUE TITLE
nr_samples_per_proposed_particle variable

### ISSUE THREAD

**Issue by EmadAlamoudi** [ICB-DCM/pyABC#352]
I was discussing with Jan and he proposes changing the variable `nr_samples_per_parameter` into `nr_samples_per_proposed_particle` to avoid confusion that may be caused by the term parameter in that context.

**Comment by yannikschaelte** [comment]
This variable will hopefully get deleted anyway soon, probably when we discard the sql database.

**Comment by stephanmg** [comment]
Closed as merged.
