### ISSUE TITLE
Trying to follow the multiscale_agent_based example (newby question)

### ISSUE THREAD

**Issue by rbelew** [ICB-DCM/pyABC#359]
I am working with the [Covasim](https://github.com/InstituteforDiseaseModeling/covasim)
simulator, and would like to apply ABC-SMC methods like your package provides to it.

I've been following along the [Tumor2d example](https://github.com/ICB-DCM/pyABC/blob/master/doc/examples/multiscale_agent_based.ipynb) and have basic calling pattern that looks like this:

```
def cvsimModel(parameter):
	return {'deaths': [1e3], 'diagnoses': [1e4] }
```

```
def main():
	bounds = dict(initInfect=(16000, 26000),
				  beta=(1e-3, 1e-2))
	
	prior = pyabc.Distribution(**{key: pyabc.RV("uniform", a, b - a)
							for key, (a,b) in bounds.items()})
	data_mean = {} # load_data()
		
	pool = ThreadPoolExecutor(max_workers=2)
	sampler = ConcurrentFutureSampler(pool)
	
	abc = pyabc.ABCSMC(cvsimModel, prior, L2Dist,
	             population_size=3,
	             sampler=sampler)
	
	db_path = "sqlite:///" + '/System/Volumes/Data/rikData/tmp/' +  "pyabcTst.db"
	runID = abc.new(db_path, data_mean)
	history = abc.run(minimum_epsilon=.1, max_nr_populations=1)
```

i'm assuming here that my cvsimModel takes 2 parameters (initInfect and
beta)  and generates two values, deaths and diagnoses, here for just
one time step.

This is throwing the error below.  But poking into the trace, it
seems it is trying to compute distances between input parameters and the
data?!  so i'm clearly doing something quite wrong.

> 
> INFO:History:Start <ABCSMC(id=5, start_time=2020-11-18 16:16:27.790701, end_time=None)>
> INFO:ABC:Calibration sample before t=0.
> Traceback (most recent call last):
>   File ".../pyABC/src/cvsim2pyABC.py", line 137, in <module>
>     history = abc.run(minimum_epsilon=.1, max_nr_populations=1)
>   File "...pyABC/lib/python3.8/site-packages/pyabc/inference/smc.py", line 606, in run
>     self._initialize_dist_eps_acc(t0)
>   File "...pyABC/lib/python3.8/site-packages/pyabc/inference/smc.py", line 428, in _initialize_dist_eps_acc
>     self.eps.initialize(
>   File "...pyABC/lib/python3.8/site-packages/pyabc/epsilon/epsilon.py", line 149, in initialize
>     weighted_distances = get_weighted_distances()
>   File "...pyABC/lib/python3.8/site-packages/pyabc/inference/smc.py", line 403, in get_initial_weighted_distances
>     population = _get_initial_population_with_distances()
>   File "...pyABC/lib/python3.8/site-packages/pyabc/inference/smc.py", line 399, in _get_initial_population_with_distances
>     population.update_distances(distance_to_ground_truth)
>   File "...pyABC/lib/python3.8/site-packages/pyabc/population.py", line 161, in update_distances
>     particle.accepted_distances[i] = distance_to_ground_truth(
>   File "...pyABC/lib/python3.8/site-packages/pyabc/inference/smc.py", line 397, in distance_to_ground_truth
>     return self.distance_function(x, self.x_0, t, par)
>   File "...pyABC/lib/python3.8/site-packages/pyabc/distance/base.py", line 241, in __call__
>     return self.fun(x, x_0)
> TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by yannikschaelte** [comment]
Hi @rbelew , sorry, I just answered your e-mail before looking at this issue. Please feel free to respond here. While I assume your model here is over-simplified, all seems to make sense, I suspect the problem lies in the definition of the distance function. Could you share its essentials?

**Comment by yannikschaelte** [comment]
Hi @rbelew , has your questions been sufficiently answered? Closing here, feel free to re-open.
