### ISSUE TITLE
Log number of "look-ahead" particles

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#360]
In the look-ahead approach, log the number of look-ahead mode samples, in particular (maybe sufficient for the moment) the number of accepted look-ahead samples, in order to be able to tell the fraction of those in the final population of each iteration.

Logging best to json/csv, via passing a filename to the sampler?

**Comment by FelipeR888** [comment]
Done with csv file. 
Needs to be called by abc.run(..., log_file=path_to_csv_file)

**Comment by yannikschaelte** [comment]
sounds good!
