### ISSUE TITLE
Time as a stopping condition

### ISSUE THREAD

**Issue by lesiwik** [ICB-DCM/pyABC#369]
Hello Guys!
Great work with pyABC!
One (small I hope) request. For some reason, I need to define the stopping condition as the time amount. I have implemented it comehow by myself but there is a problem with installing it in my jupyter notebook, upgrading up to new version and so. So the question and big big request is: would it be possible to add such a feature (adding the stopping condition as a time (in seconds)) in the official release?
Thank you in advance!!
Leszek

**Comment by yannikschaelte** [comment]
Hi @lesiwik , sure, this will be done in #370

**Comment by yannikschaelte** [comment]
There, it will be possible to pass a `from datetime import timedelta` , e.g. `timedelta(hours=2, secons=42, milliseconds=512)`. Would that work?

**Comment by lesiwik** [comment]
passing just single int (seconds) would be good enough but if passing the time delta is easier or more reasonable in your opinion it is also perfect

**Comment by yannikschaelte** [comment]
I think we need the timedelta to conveniently pass e.g. seconds, hours or days, which are all typical pyabc runtimes.

**Comment by lesiwik** [comment]
Perfect!

**Comment by yannikschaelte** [comment]
Done in #370 , release 0.10.9.
