### ISSUE TITLE
Particle weight calculation

### ISSUE THREAD

**Issue by janfb** [ICB-DCM/pyABC#383]
Hi there, and thanks for the great toolbox! 

I have been working with the toolbox a bit and wanted to understand how exactly you calculate the weights of the particles. 

I am looking for something like the following equation in the Toni et al. paper (page 3, left column): 

<img width="394" alt="image" src="https://user-images.githubusercontent.com/11921527/102228024-846df480-3eea-11eb-831b-d29f6b4a854b.png">

Or are you using a different way of calculating the weights?

**Comment by yannikschaelte** [comment]
Hi @janfb , thanks for the interest, happy to discuss. We use exactly this approach of importance sampling, with the weights being defined in https://github.com/ICB-DCM/pyABC/blob/develop/pyabc/util.py#L345 and applied in https://github.com/ICB-DCM/pyABC/blob/develop/pyabc/util.py#L258.

**Comment by janfb** [comment]
Great, exactly what I was looking for. Thanks for the quick reply! 

I am surely missing something, but why do the weights here

https://github.com/ICB-DCM/pyABC/blob/4a8f0b6608c6e136f41aa6d92c49cd87bcfc1642/pyabc/util.py#L361

showing up in the numerator, not the denominator?

**Comment by yannikschaelte** [comment]
The `acceptance_weight` is basically the multiplicative factor introduced in https://academic.oup.com/bioinformatics/article/36/Supplement_1/i551/5870512#.Xw1uW2wBPn8.twitter, Theorem 2, and only applies if the exact formulation https://pyabc.readthedocs.io/en/latest/examples/noise.html

**Comment by janfb** [comment]
Oh, I see. Make sense, thanks!

**Comment by janfb** [comment]
Sorry, I have another question. The correction with either additive noise to the simulator or the changed acceptance step as proposed in the paper, it applies only simulators that are deterministic no? 

E.g., when using just a Gaussian simulator, I wouldn't need that, would I? 

I could just use a uniform acceptor and when using `pyabc` with default settings I would just get the same weight update as in Toni et al. 2009?

**Comment by yannikschaelte** [comment]
The "changed acceptance step" can be applied to both deterministic and stochastic models. The questions is whether you can "extract" the last step of stochasticity in generating the data given certain parameters, and make a modified acceptance kernel out of that. Usually, that is measurement noise applied on top of stochastic/deterministic models.

**Comment by yannikschaelte** [comment]
So this is basically a modification of basic ABC which allows to make it exact instead of approximate, if certain parts of the model (e.g. the noise) can be extracted from the black box and defined inside pyABC.

**Comment by janfb** [comment]
ok, so you are opening the black box, cool! 
And given a stochastic model where I _can_ extract the stochasticity and use it to construct the acceptance kernel, would I then remove the noise process from the stochastic model?

**Comment by yannikschaelte** [comment]
Exactly. E.g. for an ODE it would be either "model = simulate ODE and then add random Gaussian noise" and "acceptor = UniformAcceptor", or "model = simulate ODE" and "acceptor = StochasticAcceptor" with an "kernel = StochasticNormalKernel". An often used alternative is to ignore the noise alltogether. This is more efficient and sometimes necessary, but not correct as basically perfect measurements are assumed. When accounting for noise, the "exact" version tends to be more efficient.

**Comment by janfb** [comment]
Great, thanks for the explanation, makes sense!

**Comment by yannikschaelte** [comment]
Hi @janfb , let us know if you want to discuss more details. Closing here.
