### ISSUE TITLE
Redis-Server already busy

### ISSUE THREAD

**Issue by nbungi** [ICB-DCM/pyABC#386]
Hi Yannick,

unfortunately I am running into the following error when starting pyabc.
Traceback (most recent call last):
  File "pyabc_python.py", line 137, in <module>
    history = abc.run(minimum_epsilon=5, max_nr_populations=20, min_acceptance_rate = 0.001)
  File "/home/hd/hd_hd/hd_ty170/.local/lib/python3.7/site-packages/pyabc/inference/smc.py", line 618, in run
    self.sampler.set_analysis_id(self.analysis_id)
  File "/home/hd/hd_hd/hd_ty170/.local/lib/python3.7/site-packages/pyabc/sampler/redis_eps/sampler.py", line 75, in set_analysis_id
    "The server seems busy with an analysis already")
AssertionError: The server seems busy with an analysis already

What is surprising to me is, that I don't have any other redis-server running and this error appears. Also if I use a different port, which I barely use this error appears.
The output of the redis-server itself always reads that it is
'9070:M 28 Dec 2020 12:17:01.767 * Ready to accept connections' 

Do you have any idea what may cause this error?

**Comment by yannikschaelte** [comment]
Hi @nbungi , this is from the development branch, right? Can you post the script with all pyabc calls you make? (pyabc.ABCSMC, .new, .run, ...)? For some reason, your server has an id here already and therefore seems to believe to be busy.

**Comment by nbungi** [comment]
Yes this is the development branch (commit 4a8f0b6608c6e136f41aa6d92c49cd87bcfc1642).
Here are the parts of the pyabc script w.r.t to the redis-server/pyabc calls
```

parser = argparse.ArgumentParser(description='Parse necessary arguments')
parser.add_argument('-pt', '--port', type=str, default="50004",
                    help='Which port should be used?')
parser.add_argument('-ip', '--ip', type=str,
                    help='Passed by submission scripts')
args = parser.parse_args()

redis_sampler = RedisEvalParallelSampler(host=args.ip, port=args.port, password=password, look_ahead=True, look_ahead_delay_evaluation=True, log_file='look_ahead.csv')

abc = ABCSMC(model, prior, distance, summary_statistics=sum_stat, transitions=transition, sampler=redis_sampler, population_size=pop_strategy,eps=eps)
abc.load(db, 1, r.observation("Exp"))
history = abc.run(minimum_epsilon=5, max_nr_populations=20, min_acceptance_rate = 0.001)



```

**Comment by yannikschaelte** [comment]
Ah ok, then the difference to the standard workflow seems to be that you use load() instead of new(). It is well possible that we missed a case in detecting "business" there, will have a look as there is time.

**Comment by yannikschaelte** [comment]
Hi @nbungi , in #389 I have added a test which indicates that a standard workflow with loading works without problems. What could be the difference in your case is that you manually stopped the program, leaving the server in an undefined state. In that case, calling `sampler.stop()` once may help I think. It will reset the variables indicating the server is busy and therefore allow it to start a new run.

**Comment by nbungi** [comment]
Ok, thank you for your help!
