### ISSUE TITLE
Using R in pyabc

### ISSUE THREAD

**Issue by elbaraim** [ICB-DCM/pyABC#4]
I tried to get running the example `using_R`
and I got the error that the package **external** is not found.
I came up with a solution, but I do not feel very confident yet with git to try to fix it....

This can be easily fixed by adding in `__init__.py` the following line:
from .external import R

and then include the entry `"External"`  in the array  `__all__`

This makes the example run smoothly.

**Comment by neuralyzer** [comment]
Not sure why this happens. It works on my machine - I tested it just now. But let's add a test for R usage anyways!

I think we cannot (or should not) add ``from.external import R``. R is optional. If rpy2 is not installed you should get an exception stating "Install rpy2 to enable support for the R language".  Can you post the full error message you get?

**Comment by elbaraim** [comment]
Okay, now it works. I think it was a conflict in my `/usr/local/lib/python3.5/site-packages`
I removed pyabc from there, I re-installed again and now it works perfectly.

No changes are needed :)

It was a "bug" in my local computer

**Comment by neuralyzer** [comment]
OK. Good to hear. How do you feel about adding a FAQ section to the documentation or some kind of thing where we record encountered issues and how to solve them. In particular when we cannot solve them through code such as adjusting paths?

**Comment by elbaraim** [comment]
I agree it is a very good idea 👍 

But I think any user will get this problem, since I believe the conflict was triggered by my previous installation of `pyabc` from your __neuralyzer__ repository and then installing the new from __DCM__ repository. It may be unlikely that any other user gets this issue.

Do you think it would be still interesting to include?

**Comment by neuralyzer** [comment]
Hmm. I guess we should discourage users from installing directly from git. I think this is really for experimentally minded users which do not mind if things break. The default way should be installing via pip. Maybe we need to emphasize this in the installation instructions and add a warning regarding git installation?

**Comment by elbaraim** [comment]
I don't think so. The usual way of installing python packages is through pip. I guess that most of the users will do it this way. And it is already indicated in readthedocs as recommended option.

Moreover, in the installation guide it is already included the path to the DCM repository. It should be fine 👍

**Comment by yannikschaelte** [comment]
Maybe one can add half a sentence that things may get different when installing via git / or that it is recommended to install via pypi. However, the pyabc package is organized in such a way that also experimentally minded users can do a lot without changing the core of pyabc itself :) .
