### ISSUE TITLE
Semi-decidable: pyABC refuses to quit when `epsilon` becomes too low

### ISSUE THREAD

**Issue by rbelew** [ICB-DCM/pyABC#404]
I have a simulation that reliably converges for several generations,
then sets epsilon to a level which, while discovering one or two accepted
solutions, does not find enough to satisfy the acceptance rate, minimum
epsilon, or any other termination crtieria.  Worse,
search seems to drift *away* from good solutions towards more and more
mediocre ones.

I'm unable to explicitly control the number of simulation/evaluations
using things like `max_total_nr_simulations` argument to `abc.run()`.
The reason is that these tests are made in
`termination_criteria_fulfilled` only *after* a full generation of
samples have been collected.  

I'm attaching results from a run of the  model.  Red points are individual
model evaluations, the blue lines are the values of epsilon over this
period.  (Note, i've truncated the graph after 6000 evaluations
because there is no meaningful change; they go on for 20000
evaluations in this run.) Initial search proceeds as expected, progressively reducing
epsilon with samples of better and better values.  But after the third
epsilon reduction, the bulk of samples jump UP to a mode ~150 and stay
there, with only a few below the eta threshold.  These few are
sufficient to reduce the threshold several more times with fewer
samples unrejected.  After many (~1000) additional samples at the
final threshold, *no good samples* are generated?!  
  
Other things i've tried:

- providing `check_max_eval=True` to the
  `MulticoreEvalParallelSampler` constructor
  
- I experimented with a modification to the core
  `MulticoreEvalParallelSampler.sample_until_ALL_n_accepted()`
  (attached) that puts an extra while loop around the generation of
  processes, until the set of `id_results` is as large as the `n`
  requested.  But this just seems to generate a bunch of simulations
  that never get run?!

Has anyone else bumped into behaviors like this?

<img width="744" alt="abc_210126-2-eps" src="https://user-images.githubusercontent.com/120920/106643738-023f9b00-653f-11eb-963d-5713ee4ec018.png">

```
    def sample_until_ALL_n_accepted(
            self, n, simulate_one, t, *,
            max_eval=np.inf, all_accepted=False, ana_vars=None):
        '''don't stop until a full n have been accepted
            no jabber bar
        '''

        n_eval = Value(c_longlong)
        n_eval.value = 0

        n_acc = Value(c_longlong)
        n_acc.value = 0

        queue = Queue()

        # wrap arguments
        if self.pickle:
            simulate_one = pickle.dumps(simulate_one)
        args = (simulate_one, queue,
                n_eval, n_acc, n,
                self.check_max_eval, max_eval, all_accepted,
                self._create_empty_sample)


        id_results = []

        # make sure all results are collected
        # and the queue is emptied to prevent deadlocks
        n_done = 0
        niter = 0
        
        while len(id_results) < n:
            niter += 1
            
            processes = [Process(target=work, args=args, daemon=self.daemon)
                         for _ in range(self.n_procs)]
    
            for proc in processes:
                proc.start()
            
            while n_done < len(processes):
                val = get_if_worker_healthy(processes, queue)
                if val == DONE:
                    n_done += 1
                else:
                    id_results.append(val)

            for proc in processes:
                proc.join()

        # avoid bias toward short running evaluations
        id_results.sort(key=lambda x: x[0])
        id_results = id_results[:min(len(id_results), n)]

        self.nr_evaluations_ = n_eval.value

        results = [res[1] for res in id_results]

        # create 1 to-be-returned sample from results
        sample = self._create_empty_sample()
        for result in results:
            sample += result

        print(f'sample_until_ALL_n_accepted: niter={niter}')
			
        if sample.n_accepted < n:
            sample.ok = False

        return sample

```

**Comment by EmadAlamoudi** [comment]
Hello @rbelew , Just to be sure that I understand you, you have a good acceptance rate at the earlier generations that satisfy the epsilon threshold. However, as the epsilon value decreases, more and more simulations are rejected and thus the acceptance rate for the generation can not be satisfied? if this is the case, then then it might be your observable or distance function.

**Comment by rbelew** [comment]
hi @EmadAlamoudi thanks for your response.  Yes, i believe you characterize the situation correctly.  But i'm not sure why this leads you to think there is a problem with the distance function?  The number of generated particles dwindles after the last decrease in epsilon (around gen 4600 in the plot above), and never generates enough accepted ones to trigger the tests made in `termination_criteria_fulfilled`  at the END of a full generation.  The same distance function is used throughout?

**Comment by EmadAlamoudi** [comment]
My thought about the objective function was originated from the drifting away from the good solution, and the fact that after generation (around 4660) there are hardly any particles to pass the epsilon thresh hold. However, have you tried the `min_acceptance_rate` as a termination criteria? that one should be triggered if the acceptance rate falls below a specific value.

**Comment by yannikschaelte** [comment]
Hi @rbelew , I agree with @EmadAlamoudi 's remarks here. There seem to be two things: First, you would like to control when to stop a generation due to too low acceptance rates. All criteria are indeed only checked after a generation. The `check_max_eval=True` is the only one indeed designed to stop sampling as soon as a max number of samples is exceeded. In that case, as the last generation can be anything (e.g. 0 or few accepted particles), the last generation is completely discarded. In principle it would be possible to at least save to db the few particles that got accepted.

The second point is the indeed strange behavior that at some point no points below 150 are sampled anymore. This could indicate running into a local minimum. May I ask about your problem type? What kind of model formalism, what parameters, any guesses on what the posterior might look like?

**Comment by rbelew** [comment]
Thanks for your comments @yannikschaelte .  i will do a careful experiment with `check_max_eval` and report back.

but you are right that there is a second issue that's more mysterious.  this simulation is based on [covasim](https://github.com/InstituteforDiseaseModeling/covasim), an agent-based epidemiological model.  i'm currently sampling only a few parameters (beta, initial population size, testing rate).  

if i knew the posterior... : )

**Comment by yannikschaelte** [comment]
Closing. If this is not resolved yet, please feel free to reopen!
