### ISSUE TITLE
reading summary_statistics bytes from value?

### ISSUE THREAD

**Issue by rbelew** [ICB-DCM/pyABC#415]
can someone tell me how to read out the byte string in value field of the summary_statistics table?  i can see it looks like a numpy format of some type(`b"\x93NUMPY\x01\x00v\x00{'descr': '<f8', 'fortran_order': False, 'shape': (), } ...`)  but don't know how i should read it?  thanks!

**Comment by rbelew** [comment]
i've found `r = np.frombuffer(summstat)` and it constructs a plausible array; is that it?

**Comment by EmadAlamoudi** [comment]
hello @rbelew , do you mean read the output in the database file that is related to the summary_statistics? if yes, then you can just export your database (see here: https://pyabc.readthedocs.io/en/latest/export_db.html). Then you will see the information in readable format.

**Comment by rbelew** [comment]
hello @EmadAlamoudi , thanks for your response.  i'm reading from/using the sqlite database directly via python's sqlite3 module.  the `value` field of the `summary_statistics` table is a "blob" bytestring.  using `r = np.frombuffer(summstat)` i can see it is a 1-dimensional array.  but these numbers associated with a sample seem  unrelated to the scalar distance returned by the model i pass to pyabc?

**Comment by yannikschaelte** [comment]
Hi @rbelew if you manually want to extract the data from the sql data base, in addition to @EmadAlamoudi here are the functions pyABC uses: https://github.com/ICB-DCM/pyABC/blob/develop/pyabc/storage/numpy_bytes_storage.py, and in the same folder further for pandas dataframes etc.

**Comment by rbelew** [comment]
Thank you for this pointer, @yannikschaelte .  i now understand the syntactic level of the `value` attribute.

But i am still not confused as to the relation between this VECTOR of values is built from the SCALAR value returned by the model for any sample?

**Comment by yannikschaelte** [comment]
primitive types are for convenience just also stored via numpy and converted back in l. 53ff.

**Comment by yannikschaelte** [comment]
Closing here, feel free to reopen if issue persists.
