### ISSUE TITLE
Global log level is overwritten by pyABC

### ISSUE THREAD

**Issue by lcontento** [ICB-DCM/pyABC#417]
At the moment each time the `pyabc` module is loaded the log level for the root logger is set to `INFO` (the default is `WARNING`)
https://github.com/ICB-DCM/pyABC/blob/d877a3b932b5a463965a5ca2a9911411914121f2/pyabc/__init__.py#L115-L120
This may influence the logging behaviour of other packages the user has imported, which I find not ideal.
How about using hierarchical loggers, so that the change in the loglevel can be confined to `pyabc`?

**Comment by yannikschaelte** [comment]
Sounds reasonable, but would require restructuring the many loggers used in abc.

**Comment by yannikschaelte** [comment]
I'd like to keep all logs short, but I guess the hierarchical logging may work correctly if inserting "ABC." before every logger name, tbd.
