### ISSUE TITLE
"INFO:ABC:Stopping: sample not ok" from multicore_evaluation_parallel

### ISSUE THREAD

**Issue by rbelew** [ICB-DCM/pyABC#430]
I am trying to trace back the conditions causing this message.  Can
someone explain to me the circumstances that would cause `sample.ok`
to be set to false [here](https://github.com/ICB-DCM/pyABC/blob/5dd96cfe7001ee7183b013c4c50af33233e94c48/pyabc/sampler/multicore_evaluation_parallel.py#L146)?

and no points given for "because `sample.n_accepted < n`" :)
something about `id_results` and its truncation to "avoid bias toward
short running evaluations" seems involved?  what is this comment
about, please?

**Comment by yannikschaelte** [comment]
I guess you set the  `check_max_eval` to True? sample not ok would trigger in exactly that case, indicating that the last iteration was not successful as it ran out of evaluations.

**Comment by rbelew** [comment]
indeed!  what is the "bias toward short running evaluations" you're worried about?  i realize this is getting into the multiprocessing weeds, but i can't see where `check_max_eval` causes a worked to not be healty?

**Comment by rbelew** [comment]
i should perhaps add that the running time of my model evaluations is quite consistent, so i don't think i'm not worried about "short running evaluations"?

**Comment by yannikschaelte** [comment]
The bias toward short running evaluations is due to the dynamic scheduling as introduced in https://academic.oup.com/bioinformatics/article/34/20/3591/4995841?login=true, see also https://pyabc.readthedocs.io/en/latest/sampler.html#strategies.

**Comment by rbelew** [comment]
What else might trigger the `sample.ok = False` (line 146, ./sampler/multicore_evaluation_parallel.py)  this is getting set in cases where the number of evaluation is far lower than the value `max_total_nr_simulations` specified in the `abc.run()` call?

**Comment by yannikschaelte** [comment]
Nothing else can trigger it.

**Comment by yannikschaelte** [comment]
Hi @rbelew , is this still a problem? To clarify: It is about the number of evaluations in the up-and-coming iteration, which is then not saved in the database anymore, as ok = False.

Closing here, feel free to re-open if something is still unclear!
