### ISSUE TITLE
plot_kde_matrix() and plot_history() show very different posterior/marginal distributions?

### ISSUE THREAD

**Issue by rbelew** [ICB-DCM/pyABC#432]
i've experimented with pyABC over simpler ODE models and get the satisfying set of converging posteriors as the search progress, like those shown in the pyABC tutorials (eg,
here https://pyabc.readthedocs.io/en/latest/examples/parameter_inference.html)

But now i'm running models where search has converged pretty well but seems to still have a _unifom_ posterior.  Why should the history displays of posterior distributions of parameters look so different than the marginal distributions shown on the diagonal of the kde matrix?   Samples attached.
![NZL-history](https://user-images.githubusercontent.com/120920/109720402-e095fb80-7b5e-11eb-8f2c-23932f2b56ff.png)
![NZL-kdeMatrix](https://user-images.githubusercontent.com/120920/109720404-e12e9200-7b5e-11eb-8362-927b2a45c91d.png)

**Comment by yannikschaelte** [comment]
Hi, what function are those first plots created with?

**Comment by rbelew** [comment]
plot_kde_matrix() and plot_history()

**Comment by rbelew** [comment]
here's my `plot_history()` wrapper around `plot_kde_1d`:

```
	for t in range(history.max_t+1):
		df,w = history.get_distribution(m=0, t=t)
		# HACK: need particular time's dataframe to know columns!
		if fig==None:
			paramList = list(df.columns)		
			fig, axes = pl.subplots(ncols=len(paramList))

		for i,param in enumerate(paramList):
			xmin = bounds['lb'][i]
			xmax = bounds['ub'][i]

			plot_kde_1d(df, w, x=param,label=f"t={t}", numx=300, xmin=xmin, xmax=xmax, ax=axes[i])
			axes[i].legend()
```

**Comment by rbelew** [comment]
MY BAD! the xmin/xmax bounds i was enforcing were incorrect.

**Comment by yannikschaelte** [comment]
Didn't get to writing that, but yes, that's what I would have guessed :laughing:
