### ISSUE TITLE
example is missing 4th slash in sqlite line

### ISSUE THREAD

**Issue by fbergmann** [ICB-DCM/pyABC#433]
**Bug description**
in the example in 

<https://pyabc.readthedocs.io/en/latest/examples/petab_application.html>

links are given as sqlite:///, when it should be sqlite:////

so when the example is run as is, then sqlalchemy will just fail with 

```
sqlite3.OperationalError: unable to open database file

```

**Expected behavior**
example should run

**To Reproduce**
just run the example (with the lines commented in)

**Environment**
latest pypi

**Comment by yannikschaelte** [comment]
Thanks, that is true!
