### ISSUE TITLE
Passing constant parameters to a simulation using ABCSMC

### ISSUE THREAD

**Issue by nickmalleson** [ICB-DCM/pyABC#446]
Dear pyABC team,

There may be a simple solution to this, but it has been troubling me for some time. 

I am using `pyabc.ABCSMC()` and can successfully pass RVs to my model so that ABCSMC can conduct inference.  The problem is, there are some additional _constant_ parameters (parameters that don't change) that my model relies on, and I can't figure out how to pass these as well. If I include them in my list of `parameter_priors` then `ABCSMC` will try to include them in the inference. 

What I had imagined is something like an additional argument in `pyabc.ABCSMC()` for parameters that the underlying simulation needs to know about, but ABCSMC doesn't do anything with. E.g. the `constants` argument below:

```
abc = pyabc.ABCSMC(
    models=MyModel.run_model,
    parameter_priors=my_rv_priors,
    constants={'constant_a':4, 'constant_b':1.6}
)
```

Then the `MyModel.run_model` function could be written to expect a dictionary of RVs (as it does now) and another dictionary for constant parameters.

Any suggestions about how I might be able to implement something like this? I have tried making the constants class-level variables in my simulation (e.g. setting `MyModel.constant_a=4`) before calling `abc.run()` but this doesn't seem to work with the multi-process samplers because the child processes are created with a 'blank' version of `MyModel` (e.g. one where `MyModel.constant_a` has not been set). 

Thanks in advance. This is an amazing library!

**Comment by yannikschaelte** [comment]
Hi @nickmalleson , in theory constant parameters would be something pyABC does not need to know about and which must therefore be defined inside your model, so your approach is correct. There are several ways of passing those constants into the call routine, for example the following should work:

```python
class Model:
    def __init__(self, constant_a: int = 4):
        self.constant_a = constant_a

    def __call__(self, par):
        # call your actual model
        return my_model(par, constant_a=self.constant_a)
```

**Comment by nickmalleson** [comment]
Thanks @yannikschaelte , this is a really neat solution. I wouldn't have thought to use ``__call__`` (first time I've used that python feature). Would you like me to write a short bit of documentation on this for possible inclusion in the docs? I'll close this now anyway as my particular issue has been resolved, but let me know if that would be useful.
