### ISSUE TITLE
Posterior parameter distribution as a new prior (Bayesian updating)

### ISSUE THREAD

**Issue by nickmalleson** [ICB-DCM/pyABC#468]
**Feature description**

I would like to implement a basic data assimilation scheme using pyabc. This involves running pyabc to estimate the posterior distribution of a parameter and then passing the parameter posterior distrubtion _back in to pyabc as the prior_ in a new run. At the moment I don't think this is possible because a prior must be defined using a pre-defined random variable from the `statsmodels` package, e.g.:
```
prior = pyabc.Distribution(mean=pyabc.RV("uniform", 0, 5))
abc = pyabc.ABCSMC(model, prior, distance)
``` 
rather than some arbitrary distribution.

This may already be possible through some clever inheritance of the pyabc.RV class, and I'm happy to try hacking something if anyone can give me some pointers.

**Motivation/Application**
This would allow someone to use pyabc to repeatedly update their model as new data come in, i.e. Bayesian updating / data assimilation.

**Comment by yannikschaelte** [comment]
Hi @nickmalleson , this for sure sounds very relevant. Conceptually, this should be possible without any problems, as the prior needs to be nothing but an unscaled probability distribution with rvs() and pdf(x) functions, to generate samples and evaluate densities, respectively. The class to be used / likely subclassed from is the [Distribution](https://github.com/ICB-DCM/pyABC/blob/main/pyabc/random_variables.py#L303), which has also been used to e.g. generate correlated priors. Here, you should be easily able to define a subclassed Distribution based e.g. on a [kernel density estimate](https://github.com/ICB-DCM/pyABC/blob/main/pyabc/transition/base.py#L17) (note the subclassing of transition kernels in pyABC is not perfect).

The only thing to keep in mind is pickling, i.e. the correct independent reinitialization of pseudo random number generators on parallel infrastructure. As scipy random variables at least used to be not-picklable, the initial developers of pyABC had to write that funny RV wrapper (I am actually not sure if that is still necessary).

**Comment by nickmalleson** [comment]
Thanks so much @yannikschaelte , that was really helpful. I think I have a workaround. 

I have defined an `ArbitraryDistribution` class (see below) that extends `Distribution`, but basically just has `rvs` and `pdf` functions. It takes a previous ABC history object (the output from `ABCSMC.run()`), calculates a kernel density estimate using a `MultivariateNormalTransition` and then samples from that. 

My maths is letting me down a bit, so I don't know if I am doing this correctly, but a quick test implies that the algorithm is able to converge to optimal parameters when using that `ArbitraryDistribution` rather than a normal prior defined using `pyabc.RV` objects. 

In case you're interested, my little script to test this is [on github](https://github.com/Urban-Analytics/RAMP-UA/blob/data_assimilation/experiments/calibration/pyabc_example2-bayes_update.py)

There is one problem,  as you predicted, if I try to run ABCSMC with parallel compilers it crashes, giving an error about "`Couldn't close file`". It works ok using the `SingleCoreSampler`. I haven't looked deeply into this but can't see an obvious reason why pickling would be a problem.

Anyway I'll close this issue now as I have pretty much solved my problem (although the single core sampler is a bit annoying) but if you would like me to write any of this up properly so that it can be included as an example, or so that others can try to work out what I've done wrong re. pickling, I'd be happy to.

```
class ArbitraryDistribution(Distribution):
    """
    Define an arbitrary distribution. Used so that the posterior from an ABC run can be re-used
    as the prior in a new run. Does this by taking the abc_history object (output from an
    ABC run) and generating a MultivariateNormalTransition (KDE) that can be sampled
    """

    def __init__(self, abc_history, N_samples = 1000):
        # Get the dataframe of particles (parameter point estimates) and associated weights
        self.abc_history = abc_history
        self.dist_df, self.dist_w = self.abc_history.get_distribution(m=0, t=abc_history.max_t)
        # Create a KDE using the particles
        self.kde = MultivariateNormalTransition(scaling=1)
        self.kde.fit(self.dist_df, self.dist_w)

    def rvs(self) -> Parameter:
        """Sample from the joint distribution, returning a Parameter object.
           Just calls rvs() on the underlying kde"""
        return self.kde.rvs()

    def pdf(self, x: Union[Parameter, dict]):
        """Get probability density at point `x` (product of marginals).
        Just calls pdf(x) on the underlying kde"""
        return self.kde.pdf(x)
```

**Comment by yannikschaelte** [comment]
Hi, great to hear that it is working! Mathematically, it should all be correct. As said, as prior / transition kernels more or less any non-normalized probability distributions can be used. Using the posterior from analysis on one data set as prior to another analysis on another data set is not rarely done in Bayesian inference, if the data sets are independent, as in that case the likelihood factorizes, thus in Bayes' theorem one can decompose, making sequential execution equivalent to a joint analysis of both data sets. I am not sure whether I understood the concept of assimilation here -- the same data set is used in two analyses?

Regarding multi-core sampling: the file error could be due to the abc_history saved as part of the distribution class. If you remove it (it is not really needed to keep it as an attribute, only the fitted kde), it might work already.

**Comment by nickmalleson** [comment]
Hi @yannikschaelte,

Thanks for clarifying some of the maths, I'm getting there.

> I am not sure whether I understood the concept of assimilation here -- the same data set is used in two analyses?

Not quite, you'd use data assimilation when you had new data. It's very common in meteorology to do weather forecasting (they get new weather data every few hours and update their models). In my simple example I re-use the same hypothetical observations, but in a real application you'd use it to update your parameter estimates as you get new data. 

> Regarding multi-core sampling: the file error could be due to the abc_history saved as part of the distribution class. If you remove it (it is not really needed to keep it as an attribute, only the fitted kde), it might work already.

I've had another go at this but am still a bit stuck. Here's a bit more info about the error, but I appreciate you might not be able to look at this. The full script is here: https://github.com/Urban-Analytics/RAMP-UA/blob/data_assimilation/experiments/calibration/pyabc_example2-bayes_update.py 

As you suggested, I tried removing `abc_history` from the `ArbitraryDistribution` class, and also implemented a couple of methods that I thought might be necessary (`copy` and `__repr__`) but to no avail. A slightly paraphrased version of the error output (I removed duplicate lines) is:

```
ABC.History INFO: Start <ABCSMC id=13, start_time=2021-07-07 09:36:58.714239>
ABC INFO: Calibration sample t = -1.
libc++abi: terminating with uncaught exception of type std::runtime_error: Couldn't close file
...
ABC.History INFO: Done <ABCSMC id=13, duration=0:00:05.137629, end_time=2021-07-07 09:37:03.851868>
Traceback (most recent call last):
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/sampler/multicorebase.py", line 100, in get_if_worker_healthy
    item = queue.get(True, 5)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nick/research_not_syncd/git_projects/RAMP-UA/experiments/calibration/pyabc_example2-bayes_update.py", line 250, in <module>
    abc_history = abc.run(max_nr_populations=20, minimum_epsilon=0.05)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/inference/smc.py", line 45, in wrapped_run
    ret = run(self, *args, **kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/inference/smc.py", line 651, in run
    self._initialize_dist_eps_acc(t0)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/inference/smc.py", line 460, in _initialize_dist_eps_acc
    self.acceptor.get_epsilon_config(t))
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/epsilon/epsilon.py", line 158, in initialize
    weighted_distances = get_weighted_distances()
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/inference/smc.py", line 433, in get_initial_weighted_distances
    population = _get_initial_population_with_distances()
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/inference/smc.py", line 424, in _get_initial_population_with_distances
    population = self._get_initial_population(t-1)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/inference/smc.py", line 485, in _get_initial_population
    population = self._sample_from_prior(t)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/inference/smc.py", line 514, in _sample_from_prior
    max_eval=np.inf, all_accepted=True, ana_vars=self._vars())
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/sampler/base.py", line 156, in sample_until_n_accepted
    sample = f(self, n, simulate_one, t, **kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/sampler/multicore_evaluation_parallel.py", line 122, in sample_until_n_accepted
    val = get_if_worker_healthy(processes, queue)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pyabc/sampler/multicorebase.py", line 104, in get_if_worker_healthy
    raise ProcessError("At least one worker is dead.")
multiprocessing.context.ProcessError: At least one worker is dead.
libc++abi: terminating with uncaught exception of type std::runtime_error: Couldn't close file
```

**Comment by yannikschaelte** [comment]
Thanks for the clarification. For new data, it definitely makes sense.

I ran your script, but also with the MultiCore sampler I did not get any error here. May I ask what OS you are using? For non-linux, multi-processing does not always work reliably. (Note: `copy` and `__repr__` do not help here, rather `__getstate__` and `__setstate__`, but as it works for me, I rather think it must be system-specific.

**Comment by nickmalleson** [comment]
How interesting! I'm using a mac (OS 11.4) and haven't had problems with multi-processing before, but as it works for you I agree it's almost certainty a combination of the OS or the python package versions I have. Thanks for testing it, I will experiment with some different configurations and use linux if I can't get it working on a mac. I bet the problem just disappears with either an OS or python package update some time in the future...

**Comment by yannikschaelte** [comment]
I cannot explain why sometimes the multicore sampler works and sometimes not, that is strange. One thing to try out may to to manually set pickle=True in the MulticoreEvalParallelSampler (https://github.com/ICB-DCM/pyABC/blob/main/pyabc/sampler/multicorebase.py#L24), which may be slightly less efficient, but at least enabled parallelization on some systems.

**Comment by nickmalleson** [comment]
Thanks for the suggestion @yannikschaelte . Setting `pickle=True` in the `MulticoreEvalParallelSampler` didn't help, but the script ran smoothly on linux with similar python packages (maybe not exactly identical versions as I haven't updated my anaconda environment on linux for a while, but they wont be far off).
