### ISSUE TITLE
No generation progress and ABC.Sampler INFO: Could not discard from active set 

### ISSUE THREAD

**Issue by anetzl** [ICB-DCM/pyABC#474]
Hello! I run several workers in parallel and although enough particles are accepted per generation the next generation does not start automatically. In order to start the next generation I have to manually reset the workers.
I, too, get the following error for individual workers frequently and was wondering whether these issues might be connected: 

```
ABC.Sampler INFO: Could not discard from active set: Doesn't exist.
Process Process-5:
Traceback (most recent call last):
  File "/home/bq_anetzl/.conda/envs/pyABC_ABcDModel/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/bq_anetzl/.conda/envs/pyABC_ABcDModel/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bq_anetzl/.conda/envs/pyABC_ABcDModel/lib/python3.9/site-packages/pyabc/sampler/redis_eps/cli.py", line 137, in _work
    work_on_population_dynamic(
  File "/home/bq_anetzl/.conda/envs/pyABC_ABcDModel/lib/python3.9/site-packages/pyabc/sampler/redis_eps/work.py", line 83, in work_on_population_dynamic
    while get_int(N_ACC) < get_int(N_REQ) and (
  File "/home/bq_anetzl/.conda/envs/pyABC_ABcDModel/lib/python3.9/site-packages/pyabc/sampler/redis_eps/work.py", line 36, in get_int
    return int(redis.get(idfy(var, ana_id, t)).decode())
AttributeError: 'NoneType' object has no attribute 'decode'
```

I hope you can help me figure out how to fix my problem. Thank you!

**Comment by yannikschaelte** [comment]
Dear @anetzl , this may be an error that sometimes occurs for fast-running simulations, due to parallel execution. I implemented a fix in the develop branch. Can you use `pip install git+https://github.com/icb-dcm/pyabc@develop` and let us know whether the error still occurs there?

**Comment by anetzl** [comment]
Dear @yannikschaelte , thank you very much for your quick response! I installed the develop branch implementation which fixed the `ABC.Sampler INFO: Could not discard from active set: Doesn't exist. [...] AttributeError: 'NoneType' object has no attribute 'decode' ` error. 
However, without manual reset the workers still seem to be stuck in one generation without proceeding to the next. I tried different combinations of particles and workers but this issue keeps occurring.

**Comment by yannikschaelte** [comment]
Hi, first of all now those fixes are in the main branch, pyABC version 0.11.0, so you can install it as usual. The redis sampler has a parameter `wait_for_all_samples`. Does the error still occur when you set that to `True`?

**Comment by anetzl** [comment]
Hi, I updated pyABC and ran it as recommended - it works! It takes a very long time for all workers to finish (20 h from gen 0 to gen 1 with only 10 Acceptances required) but I guess that is due to my model. Resetting the remaining workers does not give above error message. Thanks a lot!

**Comment by yannikschaelte** [comment]
Hi, good to hear it works. 10 acceptances would for usual applications be far too few (100-10000 are more common), maybe manually run you model a few times and note down average run times. pyABC has been used for anything between milliseconds and 3h, however for anything beyond a few seconds runtime, we usually use massive parallelization with a few hundred cores. If your manually calculated run time does not fit the 20h, there may still be sth wrong, e.g. with the priors, leading to many rejected particles.
