### ISSUE TITLE
Fix vector graphics in docs

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#48]
Apparently, building the docs fails due to vector graphics inclusion in latex compilation no longer being supported on the platform.

**Comment by neuralyzer** [comment]
If vector graphics means svg, then it has never been supported really. However, there is a sphinx extensions which conerts svg to formats latex can handle.

**Comment by yannikschaelte** [comment]
yes, it is svg. since recently, the rtd build passes correctly the html output, but then fails for the latex/pdf output, due to latex not being able to handle the svgs apparently

Do you know what that sphinx extension is? I tried a few at some time, but none worked so far.

**Comment by yannikschaelte** [comment]
as it seems, this could be fixed by doing nothing at all (in #53, kind of), since now readthedocs apparently allows the format again.
