### ISSUE TITLE
Unexpected behavior of kde_2d

### ISSUE THREAD

**Issue by gwosd** [ICB-DCM/pyABC#480]
**Bug description**
Using `kde_2d` on a DataFrame where the values of `x`or `y` having all the same value (which is reasonable for a discrete parameter space) return a pdf which is constant in the respective direction.

**Expected behavior**
I would assume that the pdf has a destinct peak in this dimension

**To reproduce**
```
import numpy as np
import pandas as pd
from pyabc.visualization.kde import kde_2d


# example 1
n = 10
dframe = pd.DataFrame({'a': np.linspace(0, 1, n),
                       'b': np.zeros(n)})
w = np.ones(n) / n
A, B, pdf = kde_2d(df=dframe,
                   w=w,
                   x='a',
                   y='b',
                   ymin=-1,
                   ymax=1)
```
**Environment**
pyabc   0.11.0 
python  3.8.8
MacOS 11.5.1

**Comment by EmadAlamoudi** [comment]
Hi @gwosd , Do you mean that you would like to see the peak of the `a` parameter as in the previous example? why not then use `kde_1d` for the respective direction?

**Comment by EmadAlamoudi** [comment]
Thanks for the clarification. is it possible to share the history file of that run?

**Comment by yannikschaelte** [comment]
I would like to add here that for discrete parameters, a continous kernel density estimate can imho in principle not give "appropriate" results, as it calculates variances, which for identical parameters are just zero. Therefore, in this case a histogram representation (also available in pyABC) may be better suited? Alternatively, you could try out adding little random noise, e.g. 0.01 * np.random.normal(size), to the discrete parameters.

**Comment by gwosd** [comment]
@yannikschaelte Thank you for your advice. And yes indeed, adding some noise works quiet well.
@EmadAlamoudi What exactly do you mean with sharing the history file? However, since my minimal example is sufficient to reproduce the behavior I do not think that the history is helping us much more.

And my point was more that as a user, I would like to receive an error message (such as with Scipy's pendant `scipy.stats.gaussian_kde`) and not just an incorrect result without any warning.

**Comment by EmadAlamoudi** [comment]
@gwosd great to hear that. I meant the history/the database file for that run. but anyway, that is a valid suggestion. We will try to improve that.

**Comment by yannikschaelte** [comment]
I agree -  a basic check of whether the sample is trivial should be added. @gwosd beyond checking whether all samples coincide, would you have expected any other warnings.

**Comment by gwosd** [comment]
@yannikschaelte So far, I would not expected any further checking. However, you should keep in mind, that your method fails estimating the kde for effectively 1d data. Thus, one should also check for perfectly correlated data (`a~b`). See example below.

```
import numpy as np
import pandas as pd
from pyabc.visualization.kde import kde_2d


# example 2 - perfectly correlated parameteres
n = 10
w = np.ones(n) / n
a = np.linspace(0, 1, n)
dframe = pd.DataFrame({'a': a,
                       'b': 2 * a})
A, B, pdf = kde_2d(df=dframe,
                   w=w,
                   x='a',
                   y='b')

# example 3 - after adding same noise, the method works as expected
dframe = pd.DataFrame({'a': a,
                       'b': 2 * a + 0.01 * np.random.normal(size=n)})
A, B, pdf = kde_2d(df=dframe,
                   w=w,
                   x='a',
                   y='b')
```
