### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by OscartGiles** [ICB-DCM/pyABC#5]
Small error in the documentation on this page: http://pyabc.readthedocs.io/en/latest/what.html

It reads:

> What you don’t need
> the likelihood function: p(parameter|data) is not required.
>

Should be this right?: 

> the likelihood function: p(data|parameter) is not required.

p.s. I really like this library!! Just what I needed and very easy to use so far.

**Comment by neuralyzer** [comment]
You're of course completely right. That thinks is of course already the posterior we're finally after. Thanks a lot for pointing this out.

**Comment by neuralyzer** [comment]
Closed by commit 5f3dc1624b85b2646ba0f28748f8f38670cbd871
