### ISSUE TITLE
Epsilon reinitialized when continuing a sampling run

### ISSUE THREAD

**Issue by samufi** [ICB-DCM/pyABC#507]
It can be handy to pause a sampling run to print some status information. This is easy to implement via a for-loop: 
```python
for i in range(desiredSteps):
   abc.run(max_nr_populations=1)
   # do some other stuff based on the results
```
However, unfortunately, the adaptive epsilon is always computed based on the very first sample in this case. This is counterintuitive, since everything else seems as if the sampling run is just continued (e.g. `t` is incremented). Hence, I would expect that epsilon is updated based on the most recent sample. 

The reason for this issue is the cached implementation of `_get_initial_population`:

https://github.com/ICB-DCM/pyABC/blob/913bfcf91ff68a87d8f2b5d6216047f1140b8db3/pyabc/inference/smc.py#L503

Caching like this could be fine if the method would consistently return the very first sample. However, the method takes a `t` argument, which suggests that it returns the population at a specific time. I am not to judge if this is really an issue, but for the application mentioned above, it would be nice, if the argument `t` were considered, too, when caching. E.g. the cached value would only be returned if the corresponding `t` values match.

*Quick fix:*

To solve the issue for the specific application, setting `abc._initial_population = None` prior to `abc.run` solves the problem. It would be nice if this could be done more elegantly, though.

**Comment by yannikschaelte** [comment]
> Could you specify, how things could be broken if `run` is called multiple times? Could this affect the accuracy of the results? I agree that the most elegant way would be to have each step of the while loop in a separate method that then could also be called from outside.

The point is that run() initializes various components, not only the epsilon, all of which could be not as you'd want, one would need to see in detail (in particular: distance, proposal kernel, epsilon, acceptance kernel). If that helps you, I could within the next days extract the inner loop, as well as potentially the initialization steps into separate functions, such that one can more easily loop over them. If your current setup suffices for your use case, of course fine too.

**Comment by samufi** [comment]
Having a single function for the inner loop would be awesome! (I have to say, I am very impressed by the support you are providing!) Of course I could also just copy and paste the code or modify it myself for my current project, but that might not be very sustainable. Will this change make it to PyPI within a reasonable time?

**Comment by yannikschaelte** [comment]
Thanks :) I will try to suggest a modification tomorrow, then it should be on PyPI at the latest some time next week, if that works.

**Comment by yannikschaelte** [comment]
@samufi a suggestion of decomposing the `run` function into separate functions `initialize_components_before_run`, `run_generation`, `check_terminate`, which you can call explicitly from outside is in [here](https://github.com/ICB-DCM/pyABC/blob/decompose_run/pyabc/inference/smc.py#L621), see also the diff in https://github.com/ICB-DCM/pyABC/pull/510. Not completely sure whether the design will stay this way, but this would be my suggestion. Would this work, or did you have sth different in mind?

**Comment by samufi** [comment]
Thank you @yannikschaelte! This looks perfect!
