### ISSUE TITLE
Passing my observed data to distance()

### ISSUE THREAD

**Issue by Gabriel-p** [ICB-DCM/pyABC#521]
I have a rather simple setup with a list of observed data (plus some other parameters), a custom synthetic data generator function, and a custom and distance estimator between the observed and synthetic data.

I don't understand *how* to pass the observed data to the `distance()` function. Below is a (non-working) minimal example of my setup. Could you point me on how I should modify this to make it work please?

```
import pyabc
import os
import tempfile
from . import synth_data_generator, custom_dist


# This list contains data required for the synth_data_generator() function
synth_args = [...]
# This list contains my observed data and some other objects required for
# my custom_dist() function
obs_data = [...]

def model(parameter):
    model_p = (parameter['A'], parameter['B'])
    synth_data = synth_data_generator(model_p, *synth_args)
    return synth_data

def distance(synth_data):
    return custom_dist(synth_data, obs_data)


prior = pyabc.Distribution(A=pyabc.RV("uniform", 0, 1), B=pyabc.RV("uniform", 100, 10000))
abc = pyabc.ABCSMC(model, prior, distance, population_size=10)

db_path = ("sqlite:///" + os.path.join(tempfile.gettempdir(), "test.db"))
abc.new(db_path)

history = abc.run(minimum_epsilon=.1, max_nr_populations=10)
```

**Comment by yannikschaelte** [comment]
First of all, `distance(sim, obs)` should expect simulated and observed data as arguments. https://pyabc.readthedocs.io/en/latest/api_distance.html#pyabc.distance.FunctionDistance

**Comment by Gabriel-p** [comment]
If I pass `obs_data` as a second argument to the `distance()` function, it gets overwritten. Check this working example where I added `print()` statements to see this:

```

import numpy as np
import pyabc
import os
import tempfile


def main(obs_data, synth_args):
    """
    """
    print(len(obs_data)) # <-- CHECK LENGTH HERE

    prior = pyabc.Distribution(
        A=pyabc.RV("uniform", 0, 1),
        B=pyabc.RV("uniform", 100, 10000),
    )

    def model(parameter):
        model_p = (parameter['A'], parameter['B'])
        synth_data = synth_data_generator(model_p, synth_args)
        return synth_data

    def distance(synth_data, obs_data):
        print(len(obs_data)) # <-- NOW CHECK LENGTH HERE
        return custom_dist(synth_data, obs_data)

    abc = pyabc.ABCSMC(model, prior, distance, population_size=10)

    db_path = ("sqlite:///" + os.path.join(tempfile.gettempdir(), "test.db"))
    abc.new(db_path)

    history = abc.run(minimum_epsilon=.1, max_nr_populations=10)
    breakpoint()


def synth_data_generator(model_p, synth_args):
    synth_data = np.random.uniform(4.)
    return synth_data


def custom_dist(synth_data, obs_data):
    return np.random.uniform()


if __name__ == '__main__':
    # This list contains data required for the synth_data_generator() function
    synth_args = [0.]
    # This list contains my observed data and some other objects required for
    # my custom_dist() function
    obs_data = [(3.), ("aa"), (1.)]
    main(obs_data, synth_args)

```

**Comment by Gabriel-p** [comment]
I've "fixed" it by passing a `dummy` parameter to `distance()`, but this is rather hacky. What would the proper approach to this be?

```
import numpy as np
import pyabc
import os
import tempfile


def main(obs_data, synth_args):
    """
    """
    prior = pyabc.Distribution(
        A=pyabc.RV("uniform", 0, 1),
        B=pyabc.RV("uniform", 100, 10000),
    )

    def model(parameter):
        model_p = (parameter['A'], parameter['B'])
        synth_data = synth_data_generator(model_p, synth_args)
        return {"y": synth_data}

    def distance(synth, dummy): # <-- DUMMY PARAMETER HERE
        return custom_dist(synth['y'], obs_data)

    abc = pyabc.ABCSMC(model, prior, distance, population_size=10)

    db_path = ("sqlite:///" + os.path.join(tempfile.gettempdir(), "test.db"))
    abc.new(db_path)

    history = abc.run(minimum_epsilon=-.1, max_nr_populations=10)
    breakpoint()


def synth_data_generator(model_p, synth_args):
    synth_data = np.random.uniform(4.)
    return synth_data


def custom_dist(synth_data, obs_data):
    return np.random.uniform()


if __name__ == '__main__':
    # This list contains data required for the synth_data_generator() function
    synth_args = [0.]
    # This list contains my observed data and some other objects required for
    # my custom_dist() function
    obs_data = [(3.), ("aa"), (1.)]
    main(obs_data, synth_args)
```

**Comment by yannikschaelte** [comment]
This is likely all due to the model not outputting a dictionary, which pyABC expects (that's used in all examples, but maybe not clearly documented?). I am actually surprised it even works ;). With dict output, it should all be fine.

**Comment by yannikschaelte** [comment]
Hi, orig. answer did not get saved. In snippet 2, your model returns ndarrays instead of dicts, which pyabc expects (just wrap them in a dict) and do not pass the observed data to abc.new, which is not necessary, but may cause trouble here.

**Comment by yannikschaelte** [comment]
See e.g. https://pyabc.readthedocs.io/en/latest/examples/parameter_inference.html. When using dicts as model outputs and passing the observed data to abc.new, a bivariate distance function should be easily applicable.

**Comment by Gabriel-p** [comment]
Hi, please see my third comment. That code works using `distance()` and `model()` defined like this:

```
    def model(parameter):
        model_p = (parameter['A'], parameter['B'])
        synth_data = synth_data_generator(model_p, synth_args)
        return {"y": synth_data}

    def distance(synth, dummy): # <-- DUMMY PARAMETER HERE
        return custom_dist(synth['y'], obs_data)
```

Notice that `model()` returns a dict, but `distance()` still requires a second parameter that I do not not how to pass (hence the `dummy` argument). In the [example](https://pyabc.readthedocs.io/en/latest/examples/parameter_inference.html) the distance function is defined as:

```
def distance(x, y):
    return abs(x["data"] - y["data"])
```

but I don't understand where do `x` and `y` come from. That example si not at all clear to me, sorry.

------------------------
"*do not pass the observed data to abc.new*" but I'm not using `abc.new()`?

**Comment by Gabriel-p** [comment]
Thank you very much @yannikschaelte, I understand the mechanics now

**Comment by yannikschaelte** [comment]
You are welcome! Please let us know if anything else is unclear or if you miss something.

**Comment by yannikschaelte** [comment]
Dear @Gabriel-p , the examples section has been re-organized and extended by references https://pyabc.readthedocs.io/en/latest/examples/parameter_inference.html, I hope it is clearer now.

**Comment by Gabriel-p** [comment]
Thank you Yannik
