### ISSUE TITLE
Termination if epsilon change is too small

### ISSUE THREAD

**Issue by rbelew** [ICB-DCM/pyABC#522]
**Feature description**

I've found it useful to terminate runs when the change in epsilon between generations falls below some threshold.  i've done a couple of local hacks to `pyabc.util.py` and `pyabc.inference.smc.py` that accomplish this for me, but i'm sure it can be done more elegantly.

* `smc.ABCSMC.__init` line#239
```
self.prevEps = None
```

* `smc.ABCSMC.run` line#736
```
self.prevEps = current_eps
```
* `util.termination_criteria_fulfilled` line#615

```
    elif prevEps != None and type(prevEps) == type(np.float64(1.0)) and prevEps - current_eps < 1e-4:
        logger.info(f"Stopping: change in eps < 1e-4")
        return True
```

**Motivation/Application**
I realize any threshold (1e-4 in my example) will be arbitrary and problem-dependent.  But i've found this test to reliably stop runs after reasonable progress when other termination criteria could not be used.

**Comment by yannikschaelte** [comment]
@rbelew this feature will be added in #525 and part of release 0.11.8

**Comment by rbelew** [comment]
great, looking forwrd to it!
