### ISSUE TITLE
AttributeError: module 'pyabc' has no attribute 'sge'

### ISSUE THREAD

**Issue by Gabriel-p** [ICB-DCM/pyABC#535]
**Bug description**
Tried to check the number of available cores with

    pyabc.sge.nr_cores_available()

as described in the [docs](https://pyabc.readthedocs.io/en/latest/api_sge.html#pyabc.sge.nr_cores_available). Got this:

    AttributeError: module 'pyabc' has no attribute 'sge'

**Expected behavior**
An integer should be returned

**To reproduce**
Use the above command

**Environment**
[Report at least the pyABC version (`pip show pyabc`),
python version (`which python; python --version`),
and system (Ubuntu/Mac/...).]

```
$ pip show pyabc
Name: pyabc
Version: 0.11.7
Summary: Distributed, likelihood-free ABC-SMC inference
Home-page: https://github.com/icb-dcm/pyabc
Author: The pyABC developers
Author-email: yannik.schaelte@gmail.com
License: BSD-3-Clause
Location: /home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages
Requires: sqlalchemy, redis, scikit-learn, cloudpickle, jabbar, click, numpy, matplotlib, scipy, distributed, pandas, gitpython
Required-by: 
```

elementary OS 5.1.7 (based on Ubuntu 18.04.6 LT), Linux 5.5.0-050500-generic

```
$ which python; python --version
/home/gabriel/miniconda3/envs/asteca/bin/python
Python 3.9.7
```

**Comment by yannikschaelte** [comment]
You need to explicitly `import pyabc.sge` (similar to e.g. scipy.stats), as this is a submodule outside pyABC's core functionality and thus not automatically imported.

**Comment by Gabriel-p** [comment]
You are absolutely right, thank you!
