### ISSUE TITLE
Uniform prior and posterior

### ISSUE THREAD

**Issue by aakhmetz** [ICB-DCM/pyABC#553]
Hello,

I apology for a beginner question. When I try to implement a uniform prior:
```
σ1 = RV("uniform", 10, 50)
```
my understanding was that posterior distribution of σ1 should also not go beyond the limits, but it goes:
![image](https://user-images.githubusercontent.com/2173206/158322419-4ab2e8a1-d63f-4918-8201-06ceceb62e15.png)

Even with zero step, the value of  σ1 starts from zero. I could expect that ```pyabc.visualization.plot_kde_1d``` gives some smoothing, but I thought it should not be that big.

**Comment by yannikschaelte** [comment]
Hi, indeed for `RV("uniform", 10, 50)` values should only be in the range (10, 60). Can you try a different KDE, e.g. GridSearchCV, or plot a histogram? You can also manually inspect all values you get from history.get_distribution().

**Comment by aakhmetz** [comment]
Thank you for quick response - yes, the problem appears to be with plotting. 

I tried to do:
```
vals = history.get_distribution()[0].σ1.values
[np.min(vals), np.max(vals)]
```
which gave me:
```
[12.89318039049677, 46.2814970481375]
```

The GridSearchCV has not changed the output
![image](https://user-images.githubusercontent.com/2173206/158347738-8cad8d5d-8142-417e-b42b-da4cb0d4b010.png)
