### ISSUE TITLE
How can I set constraints between model parameters?

### ISSUE THREAD

**Issue by xieduo7** [ICB-DCM/pyABC#558]
Hi, the developers and users of pyABC,

Can pyABC support any function which can express constraints between model parameters? 

For example, I want to estimate two parameters (theta1 and theta2) using pyABC, and I want to set a constriant condition in these two parameters (theta1 > theta2) when I randomly choose prior parameters (theta1 and theta2). If it is not the case, this prior sampling will not pass to the ABC function. 

I  know there is a `prior_test` option in the [ABC_sequential](https://www.rdocumentation.org/packages/EasyABC/versions/1.5/topics/ABC_sequential) function of R package `EasyABC` which can do this. Is there any equivalent to the `prior_test` option of EasyABC in pyABC? 

I have tried to add a line of conditional code but it didn't work well:
```
def model(theta1, theta2):
    if theta1 > theta2:
       do something
       return something
    else:
      return None
```
Do you have any suggestions? Or should I modify the source code of the pyABC package?
Thank you!

Best,
Duo

**Comment by xieduo7** [comment]
Hi @yannikschaelte,

Thank you for your quick response. Looking forward to the notebook!

Best,
Duo

**Comment by yannikschaelte** [comment]
Dear @xieduo7 , an example is now given in https://pyabc.readthedocs.io/en/develop/examples/custom_priors.html

**Comment by xieduo7** [comment]
Hi @yannikschaelte,

Thank you for your example. I will try it!

Best,
Duo
