### ISSUE TITLE
How to get the estimated parameter?

### ISSUE THREAD

**Issue by xieduo7** [ICB-DCM/pyABC#564]
Hi developers,

I am using pyabc to estimate the parameters of models. I have a question: do you have any suggestions to get the best-estimated parameter based on the last generation of the population? For example, how can I get the location of the top of the slope? 
<img width="460" alt="image" src="https://user-images.githubusercontent.com/35059160/165256553-f77e5562-1fbc-4597-8b02-91adf4cbb1af.png">

Do you have any suggestions?

Thank you.

Best,
Duo

**Comment by yannikschaelte** [comment]
Hi, getting the top value would imply an optimization, which you can e.g. perform using `scipy.optimize.minimize` on a KDE (which you can obtain via `pyabc.transitions` kernels, e.g. a MultivariateNormal).

However, in a Bayesian context, you are usually rather interested in integral statistics such as the posterior mean and variance. These you can obtain via e.g. `pyabc.weighted_mean`, passing values and weights obtained via `history.get_distribution()`.

**Comment by yannikschaelte** [comment]
Closing here due to inactivity, but feel free to re-open if issues persist!

**Comment by xieduo7** [comment]
Sorry for the late respone. I have tried these methods and these work.

Thank you!

Duo
