### ISSUE TITLE
JOSS Review - Error when running automated tests

### ISSUE THREAD

**Issue by blakeaw** [ICB-DCM/pyABC#565]
Hi,

This issue is part of the JOSS Review at https://github.com/openjournals/joss-reviews/issues/4304

I ran into an error when I tried to run the base automated tests with `tox -e base` as described in the docs at https://pyabc.readthedocs.io/en/latest/contribute.html#unit-tests

After then running `pytest base` I saw I was missing r2py and pyarrow, which are dependencies for the R interface `pip install pyabc[R]`.  

A couple of comments:
1. Maybe pytest should be part of the dev requirements installed with `pip install -r requirements-dev.txt` since it doesn't seem to be installed otherwise. Or it could be noted more clearly in docs that you need to install pytest to locally run automated tests (even when doing so via tox).  
2.  Since the R interface is an optional part of the package it might be helpful to note in the Contribute section of the docs that it has coverage in the base tests (`tox -e base` or `pytest base`) and needs to be installed for the relevant tests to pass (along with an R distribution).

**Comment by yannikschaelte** [comment]
Thanks for the issue! Indeed, pytest is not intended to be run on its own, but our whole workflow uses tox, which is thus the only requirement in requirements-dev.txt. I see how this documentation line can be misunderstood, will clarify that pytest is needed to locally run tests.

Regarding R dependencies: Yes, each test set has some requirements, which can e.g. be found in the tox.ini file. I will add a clarification for that.

Indeed R needs a separate installation, as does julia. I will clarify that.
