### ISSUE TITLE
Is this description wrong in the documention?

### ISSUE THREAD

**Issue by xieduo7** [ICB-DCM/pyABC#592]
**Bug description**

Hi  @yannikschaelte ,

In the description of PNormDistance [documention](https://pyabc.readthedocs.io/en/latest/api_distance.html#pyabc.distance.PNormDistance), the `p=1 for a Euclidean or L1 metric, * p=2 for a Manhattan or L2 metric`. But according to the equation of distance, it should be  `p=2 for a Euclidean, * p=1 for a Manhattan`. Am I right?

Thank you!

Best,
Duo

**Comment by yannikschaelte** [comment]
Hi, thank you for pointing this out, this is indeed a mistake, it should be 2->Euclidean, 1->Manhattan.
