### ISSUE TITLE
Epsilon not taken from old database when continuing a run with abc.load()

### ISSUE THREAD

**Issue by anetzl** [ICB-DCM/pyABC#594]
Hi!

I am trying to continue an ABC-SMS run that was ended due to a time limit. I can load the old database using abc.load(), and when I start the run the population number (t) is correct. However, the initial epsilon is not the epsilon from the last generation of the old database.

If I pass an initial epsilon to ABCSMC, this initial epsilon is taken for the continued run (which I for now manually adjust to match the old database's last eps). If I don't pass an epsilon, the run starts with a calibration generation. Do you have an idea what might be causing my problem?

Many thanks!

**Comment by yannikschaelte** [comment]
In case this does not solve your issue: Could you post your code, in particular what type of distance you use and how you initialize the ABCSMC objects?

**Comment by anetzl** [comment]
Hi! 
thanks for the responses. My model and distance are written in R. 

Here is my code

```
# Source R file with functions
r = R(os.path.join(save_in, 'ferret_pyabc.R'))
# External model (immune_generator_ferret_pyabc)
model = r.model('immune_generator_ferret_pyabc')
# External distance function (cumulative_distance_sim_to_exp)
distance = r.distance('cumulative_distance_sim_to_exp')

# Population strategy for the ABCSMC
pop_strategy = populationstrategy.ConstantPopulationSize(nr_particles = n_part_gen) # n_part_gen is variable, For testing purposes I set it to 100, otherwise to 500

# Here I set the epsilon manually to the epsilon of the old database, otherwise I start with 1e7                                                     
eps = pyabc.QuantileEpsilon(initial_epsilon = 1.73241073e+04, #10000000,
                            alpha=0.55)

# Generate priors according to the argument parameters and the transition mapping
prior = Distribution()
mapping = {}
for i in parameters:  # parameters to fit are passed to python in bash script
    prior[i] = RV('uniform', lower_bounds[i], upper_bounds[i])
    mapping[i] = pyabc.MultivariateNormalTransition()

transition = pyabc.transition.AggregatedTransition(mapping=mapping)

# Redis sampler
redis_sampler = RedisEvalParallelSampler(host = ip,
                                         port = port,
                                         password = password,
                                         wait_for_all_samples = True)

# set ABC inference model 
abc = ABCSMC(models = model,
             parameter_priors = prior,
             distance_function = distance,
             transitions = transition,
             sampler = redis_sampler,
             population_size = pop_strategy,
             eps = eps)

# Database
db = 'sqlite:///' + os.path.join(save_in, '{}.db'.format(db_name))

# Here I load the old db
old_db_name = 'sim_1inj_1000p_1e7e'

old_db_dir = os.path.join(current_dir, 'data/ferret_data/parameter_fit/', old_db_name)
old_db = 'sqlite:///' + os.path.join(old_db_dir, '{}.db'.format(old_db_name))
old_his = History(old_db)
abc.load(old_db, old_his.id,
	observed_sum_stat = r.observation('experiments'))

# Run ABC
history = abc.run(minimum_epsilon = 0.5)
```

And then it starts the correct generation, but with the value that I assign to initial_epsilon. If I don't set an initial epsilon, it starts with a calibration generation.
Thanks!

**Comment by EmadAlamoudi** [comment]
using the epsilon when constructing the ABCSMC object will lead to continuing the run from the last generation while ignoring the epsilon of the last healthy generation. Could you share the logging output of the original run + the continuation run (without assigning `eps`)?

**Comment by anetzl** [comment]
Thank you, it seems to have worked now but the epsilons are not the same. Except for removing the ```eps``` from the ABCSMC initialisation I kept all as above. That is correct? 

Here is the log from the original run:

```
ABC.History INFO: Start <ABCSMC id=1, start_time=2022-12-21 11:55:46>
ABC INFO: t: 0, eps: 1.00000000e+07.
ABC INFO: Accepted: 1000 / 1041 = 9.6061e-01, ESS: 1.0000e+03.
ABC INFO: t: 1, eps: 1.73241073e+04.
ABC.History INFO: Done <ABCSMC id=1, duration=4 days, 23:58:27.290983, end_time=2022-12-26 11:54:13>
```

And this is the one from the ABCSMS without any epsilon:
```
ABC INFO: t: 1, eps: 1.34615030e+04.
```

**Comment by EmadAlamoudi** [comment]
You still can use the `eps` on the original run, but when continuing, you need to remove it. 

I think that the difference in epsilon is due to the `alpha` that you define in the original run `alpha=0.55`. Because if not given, a quantile will be taken instead. 

Remember, you can always continue the run in a manual way, by manually adjusting the `eps` to match the original run's last `eps`
