### ISSUE TITLE
Adaptive Distances: Only record all summary statistics when needed

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#6]
Make samplers process and return only required summary statistics, in order to avoid communication overhead if distance functions only need the accepted summary statistics, but not all sampled summary statistics.

**Comment by yannikschaelte** [comment]
so now in the feature branch the distance function has a flag accepted which is checked in smc. it would need to be passed to the sampler as well somehow (i.e. give sampler an additional argument record_all_summary_statistics) in order to reduce the number of recorded particles as far as possible

**Comment by neuralyzer** [comment]
I guess a flag should work for now. Just wondering whether it might be a more extensible solution (and I think also not much more work) to have instead some kind of summary statistics recorded and possibly a factory for them to have them implement the strategy how to handle non accepted summary statistics. This would make it rather easy to also add thing like only save the first let's say 1000 summary statistics, or none, or all or every tenth. This kind of recorder could probably be part of the Sample class? So you'd do always sample.add(...) and some sample classes could choose to ignore rejected ones, add only 1000 rejected ones or whatever. What do you think?

**Comment by yannikschaelte** [comment]
So we can pass a class SamplerOptions to the sampler, which can extensibly carry all information? This could then be passed to the Sample, where e.g. different summary_statistics recording strategies can be employed.

**Comment by neuralyzer** [comment]
Could we just pass a Sample class to the sampler? The Sample class does the recording anyways?

**Comment by yannikschaelte** [comment]
Also nice, I am just wondering how things work with the parallelization since that object would need to be passed to all workers.

**Comment by neuralyzer** [comment]
That is true. In principle this is not a problem. A class is also just another Python object. In particular when it is defined in a source file it is not problematic to pickle it. In terms of how it is passed, I'm not entirely sure yet. Maybe this whole thing of the sample_one and simulate_one functions goes away and is instead replaced by some object, which holds these two functions and the Sample class. Wondering whether the single core sampler could be the thing. Could we then maybe pass/serialize the SingleCoreSampler and push it to the workers? This could help to get rid of some repetetive code. The different samplers are unfortunately a little repetetive in terms of their code. But we'll have to see if that works of whether we're getting lost in abstractions over abstractions.

**Comment by yannikschaelte** [comment]
If we have an object passed to the Sampler anyway, it totally makes sense to include also the sample_one and simulate_one methods in it. I would guess that we can get problems when different workers start writing on the same e.g. list, so I would recommend keeping the branch-and-gather architecture, i.e. that workers generate some separate objects which are then in the end aggregated by the Sampler to one output, the Sample. 
It would definitely be nice if we can remove repetitive code from the different samplers, just not sure how far that is possible, because the different samplers seem to need to pursue different strategies and update different types of counting variables.

**Comment by neuralyzer** [comment]
I'm also not sure how much we can abstract. Too much abstraction can overcomplicate the code and we don't want that :)
I think the workers could just get the same object and pass its results back to be then recombined? For example, if that new mysterious object was the SingleCoreSampler, which already returns a Sample, then then in the distributed setting, the workers could each run a SingleCoreSampler and return the Samples back over the network. The master would then only combine these Samples. In this case, the sample class does need to know how to aggregate. But it mostly knows this already because it is implemented in the Sample.append and Sample.__add__ functions.

**Comment by neuralyzer** [comment]
Not so sure whether the Sample class should get SampleOptions. Isn't it enough to only pass this to the Sampler? How do you feel about using the SingleCoreSampler as the ``SampleOptions`` thing. Pure data classes such as the SampleOptions might have their place but I'd rather think twice about adding such a thing.

**Comment by yannikschaelte** [comment]
Sure. I will try how this can be done. If you like, you could also try if the SingleCoreSampler can be used in this way, since you will know better how the different samplers need to communicate between workers and what can be pickled.
It is definitely good to decide on a format now, because in case users implement own Samplers, we should have not too many interface breaks.

**Comment by neuralyzer** [comment]
Yup. Need to check. It is already done int he multicore particle parallel sampler https://github.com/ICB-DCM/pyABC/blob/dde348a85288302056b63baf571abd268462a10c/pyabc/sampler/multicore.py#L26 Let's check if it generalizes, it is certainly not as straigtforward for the evaluation parallel ones, but it might have the nice side effect that batch sampling becomes available for the evaluation parallel samplers ones in a nicer way.

**Comment by yannikschaelte** [comment]
So now the whole thing has been implemented in the feature branch. To see whether it works, first everything was put into an SamplingOptions object. The relevant information for the Sample is then put ahead to the Sample. This reduces the code duplication for the samplers, as all action can happen inside the Sample.
It seems to work with all samplers, including pickling, and the data storage is reduced as far as possible, i.e. it is only saved what is required to be saved. So now a second step could be to integrate this with the SingleCoreSampler somehow.
