### ISSUE TITLE
AssertionError: The population total weight nan is not normalized.

### ISSUE THREAD

**Issue by MJKampmann** [ICB-DCM/pyABC#614]
Hi, 
I am trying to run a model written in R with pyABC. After a number of populations the run stops with the following error message:

`/Users/martin/miniconda3/envs/spyder-kernel/lib/python3.11/site-packages/pyabc/inference_util/inference_util.py:346: RuntimeWarning: divide by zero encountered in scalar divide
  weight = acceptance_weight * prior_pd / transition_pd
/Users/martin/miniconda3/envs/spyder-kernel/lib/python3.11/site-packages/pyabc/population/population.py:415: RuntimeWarning: invalid value encountered in scalar divide
  p.weight /= total_weight_accepted`

`File ~/miniconda3/envs/spyder-kernel/lib/python3.11/site-packages/pyabc/population/population.py:98 in __init__
    raise AssertionError(
AssertionError: The population total weight nan is not normalized.`

What seems to be happening is that the model total weight increases to infinity at some point. The number of generations varies, sometimes it's after two sometimes more, sometimes after 10.

The model is written in r, so I am using rpy2 to use it with pyABC, basically all I am doing in pyABC is this: 

`r = R("pyABC_myModel.R")`
`model = r.model("myModel")`
`distance = r.distance("myDistance")`
`abc = ABCSMC(model, prior, distance)`
`abc.new(db,r.observation("myData")`
`history = abc.run(minimum_epsilon=0.01, max_nr_populations=50)
`
These are the versions etc I am using:
Python 3.11.4, pyabc 0.12.11, rpy2 3.5.13 on a Mac M1

Any help what could be causing that issue would be greatly appreciated.

Thanks.

**Comment by stephanmg** [comment]
Hello @MJKampmann,

could you please try the latest pyabc 0.12.12 please?

Also, could you show the model `pyABC_myModel.R` if not confidential.

**Comment by arrjon** [comment]
The problem seems to lie in the transition kernel. Changing to a local transition instead of using a multivariate normal kernel seems to solve the issue:
```
abc = pyabc.ABCSMC(model, prior, distance, 
                   transitions= pyabc.LocalTransition(),
                   summary_statistics=summary_statistics, population_size=50)
```
The transition kernel should ideally be kind of similar as the unknown posterior. You can find more details here in this nice [paper](https://www.degruyter.com/document/doi/10.1515/sagmb-2012-0069/html).

**Comment by stephanmg** [comment]
Feel free to re-open if @arrjon's solution does not work.
