### ISSUE TITLE
AttributeError: 'OptionEngine' object has no attribute 'execute' 

### ISSUE THREAD

**Issue by jack-pan-ai** [ICB-DCM/pyABC#621]
**Bug description**
AttributeError: 'OptionEngine' object has no attribute 'execute' 

**Expected behavior**
There should be no problem with the inference .run() module

**To reproduce**
In the parameter_inference example, https://pyabc.readthedocs.io/en/latest/examples/parameter_inference.html

**Environment**
[Report at least the pyABC version (`pip show pyabc`),
Name: pyabc
Version: 0.12.12
Summary: Distributed, likelihood-free ABC-SMC inference
Home-page: https://github.com/icb-dcm/pyabc
Author: The pyABC developers
Author-email: yannik.schaelte@gmail.com
License: BSD-3-Clause
Location: /Users/panq/miniconda3/envs/pytorch/lib/python3.9/site-packages
Requires: matplotlib, scikit-learn, scipy, redis, click, sqlalchemy, gitpython, jabbar, cloudpickle, numpy, pandas, distributed
Required-by:
python version (`which python; python --version`),
Python 3.9.7
and system (Ubuntu/Mac/...).]
MacBook Pro 2.3 GHz 8-Core Intel Core i9

**How to fix**
in `./setup.cfg`
The latest version of SQLAlchemy (2.0) has removed Engine.execute. For the time being you may need to downgrade SQLAlchemy
`sqlalchemy<2.0`
https://stackoverflow.com/questions/75309237/read-sql-query-throws-optionengine-object-has-no-attribute-execute-with

**Comment by stephanmg** [comment]
@jack-pan-ai thanks for reporting. For now we will try downgrading to sqlalchemy < 2.0 if nothing breaks.

**Comment by stephanmg** [comment]
Should be fixed. Feel free to re-open if error persists.
